In [1]:
from sklearn.tree import DecisionTreeRegressor 
import pandas as pd
from sklearn.cross_validation import KFold
import sklearn as sk
import numpy as np

target_file = 'life expectancy by country and year.csv'
HIV_file = 'HIV rates by country and year.csv'
Income_file = 'Income per capita by country and year.csv'
Internet_file = 'Internet user rates by country and year.csv'
Continent_file = 'Continent.csv'
health_data = 'health_data.csv'

In [2]:
input_df = pd.read_csv(input_file)
target_df = pd.read_csv(target_file)
HIV_df = pd.read_csv(HIV_file)
Income_df = pd.read_csv(Income_file)
Internet_df = pd.read_csv(Internet_file)
Continent_df = pd.read_csv(Continent_file)
health_df = pd.read_csv(health_data)
health_df = health_df.iloc[:-5, :]

In [3]:
# input_df
# health_df.head()

In [4]:
# null_data = target_df[target_df.isnull().any(axis=1)]

In [5]:
# null_data.head()

In [6]:
worldbank_life_exp = pd.read_csv('worldbank_life_exp.csv')
val_set = worldbank_life_exp[['Country Name', '1960', '2011', '2012', '2013', '2014']]
val_set_final = val_set.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
countries = target_df['Country Name'].values
VALIDATION = val_set_final[val_set_final['Country Name'].isin(countries)]
VALIDATION.head()

           Country Name       1960       2011       2012       2013       2014
0                 Aruba  65.569366  75.081390  75.205756  75.328659  75.451098
2           Afghanistan  32.328512  59.327951  59.679610  60.028268  60.374463
3                Angola  32.984829  51.059317  51.464000  51.866171  52.266878
4               Albania  62.254366  77.240585  77.443976  77.640463  77.830463
6  United Arab Emirates  52.243220  76.851195  77.024146  77.195634  77.368171

In [7]:
GDP_growth = pd.read_csv('GDP_Growth.csv')
GDP_growth.drop(GDP_growth.columns[[1,2,3]], axis=1, inplace=True)
GDP_growth.loc[GDP_growth['Country Name'] == 'Korea, Dem. People\x89\xdb\xaas Rep.', 'Country Name'] = 'Korea, Dem. People\xe2\x80\x99s Rep.'
GDP_growth = GDP_growth[GDP_growth['Country Name'].isin(input_df['Country Name'].values)]


MORT_U5 = pd.read_csv('MORT_U5.csv')
MORT_U5.drop(MORT_U5.columns[[1,2,3]], axis=1, inplace=True)
MORT_U5.loc[MORT_U5['Country Name'] == 'Korea, Dem. People\x89\xdb\xaas Rep.', 'Country Name'] = 'Korea, Dem. People\xe2\x80\x99s Rep.'
MORT_U5 = MORT_U5[MORT_U5['Country Name'].isin(countries)]

In [303]:
# MORT_U5.head()

In [9]:
Target_Columns = ['Country Name']+ [str(year) for  year in range(1950,2017)]
target_df_final = pd.DataFrame()
for year in Target_Columns:
    if year in target_df.columns:
        target_df_final['%s' % (year,)] = target_df['%s' % (year,)]
    else:
        target_df_final['%s' % (year,)] = np.nan

In [10]:
Input_Columns = ['Country Name']+ [str(year) for  year in range(1950,2017)]
input_df_final = pd.DataFrame()
for year in Input_Columns:
    if year in MORT_U5.columns:
        input_df_final['%s' % (year,)] = MORT_U5['%s' % (year,)]
    else:
        input_df_final['%s' % (year,)] = np.nan

In [11]:
input_df_final.fillna(0.0, inplace=True)

In [12]:
input_df_final

,Country Name,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,113.2,110.4,107.6,105.0,102.3,99.5,96.7,93.9,91.1,0.0
3,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,196.4,192.0,187.3,182.5,177.3,172.2,167.1,162.2,156.9,0.0
4,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18.7,17.9,17.3,16.6,16.0,15.5,14.9,14.4,14.0,0.0
6,United Arab Emirates,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.4,9.1,8.8,8.5,8.2,7.8,7.4,7.1,6.8,0.0
7,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.8,15.4,15.0,14.6,14.2,13.8,13.3,12.9,12.5,0.0
8,Armenia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.1,20.0,19.0,18.0,17.2,16.3,15.5,14.7,14.1,0.0
10,Antigua and Barbuda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.3,10.9,10.4,9.9,9.5,9.1,8.7,8.4,8.1,0.0
11,Australia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.4,5.2,5.0,4.8,4.5,4.3,4.1,3.9,3.8,0.0
12,Austria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.7,4.6,4.5,4.4,4.2,4.0,3.9,3.7,3.5,0.0
13,Azerbaijan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,45.8,43.3,41.0,39.0,37.3,35.7,34.2,32.9,31.7,0.0
14,Burundi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,114.5,108.6,103.5,98.8,94.9,91.2,87.8,84.6,81.7,0.0
15,Belgium,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.8,4.7,4.6,4.5,4.4,4.3,4.3,4.2,4.1,0.0
16,Benin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,119.0,116.3,113.9,111.6,109.3,107.0,104.8,102.1,99.5,0.0
17,Burkina Faso,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,139.9,130.4,121.4,113.5,106.9,101.4,96.6,92.4,88.6,0.0
18,Bangladesh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,59.4,55.9,52.6,49.6,46.7,44.0,41.6,39.5,37.6,0.0
19,Bulgaria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.2,13.7,13.3,13.0,12.6,12.0,11.5,10.9,10.4,0.0
20,Bahrain,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,9.4,8.8,8.3,7.8,7.3,6.9,6.5,6.2,0.0
21,"Bahamas, The",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.8,14.5,14.2,13.9,13.5,13.2,12.8,12.4,12.1,0.0
22,Bosnia and Herzegovina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.3,8.1,7.8,7.4,6.9,6.5,6.1,5.7,5.4,0.0
23,Belarus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.9,7.2,6.6,6.1,5.6,5.3,5.0,4.7,4.6,0.0
24,Belize,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.6,20.1,19.5,19.0,18.5,18.0,17.5,17.0,16.5,0.0
25,Bermuda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,Bolivia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,54.9,52.0,49.3,47.0,44.9,43.1,41.3,39.8,38.4,0.0
27,Brazil,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,19.2,18.1,17.2,16.6,16.2,16.0,16.0,16.2,16.4,0.0
28,Barbados,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.8,15.4,15.1,14.7,14.4,14.1,13.7,13.3,13.0,0.0
29,Brunei Darussalam,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,9.0,9.1,9.3,9.5,9.7,9.9,10.1,10.2,0.0
30,Bhutan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,51.3,48.1,45.1,42.3,39.9,37.8,36.0,34.4,32.9,0.0
31,Botswana,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,62.6,61.7,57.3,53.5,51.8,49.5,46.6,44.8,43.6,0.0
32,Central African Republic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,161.3,158.2,154.2,150.2,146.2,142.1,138.5,134.0,130.1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,Seychelles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.2,14.2,14.2,14.2,14.2,14.2,14.0,13.8,13.6,0.0
224,Syrian Arab Republic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,17.3,16.5,15.9,15.3,15.0,16.0,15.3,14.3,12.9,0.0
226,Chad,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,171.5,168.0,164.0,160.1,156.0,151.6,147.1,142.9,138.7,0.0
229,Togo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,99.2,96.4,93.6,90.9,88.3,85.8,83.3,80.8,78.4,0.0
230,Thailand,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.3,15.6,15.0,14.5,14.0,13.5,13.1,12.6,12.3,0.0
231,Tajikistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,58.6,56.2,54.3,52.6,50.9,49.3,47.8,46.3,44.8,0.0
232,Turkmenistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,66.0,63.9,61.9,60.1,58.2,56.5,54.7,53.1,51.4,0.0
235,Timor-Leste,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,74.1,70.2,66.7,63.8,61.1,58.7,56.5,54.5,52.6,0.0
236,Tonga,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.8,17.0,17.2,17.4,17.5,17.5,17.3,17.1,16.7,0.0
239,Trinidad and Tobago,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.6,24.9,24.3,23.6,22.9,22.2,21.5,20.9,20.4,0.0
240,Tunisia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.5,19.4,18.3,17.4,16.5,15.8,15.2,14.6,14.0,0.0
241,Turkey,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.9,22.2,20.6,19.1,17.8,16.5,15.4,14.3,13.5,0.0
243,Tanzania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,79.5,73.7,68.6,63.4,58.9,55.7,53.3,50.5,48.7,0.0
244,Uganda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,92.5,85.9,80.1,75.2,69.8,64.1,60.3,56.9,54.6,0.0
245,Ukraine,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13.4,12.9,12.3,11.8,11.2,10.6,10.0,9.5,9.0,0.0
247,Uruguay,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13.3,13.0,12.7,12.3,12.0,11.6,11.1,10.6,10.1,0.0
248,United States,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.8,7.7,7.5,7.4,7.2,7.1,6.9,6.7,6.5,0.0
249,Uzbekistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,50.8,49.2,47.6,46.1,44.6,43.2,41.8,40.4,39.1,0.0
250,St. Vincent and the Grenadines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.6,21.4,21.1,20.8,20.3,19.8,19.3,18.8,18.3,0.0
251,"Venezuela, RB",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,17.4,17.1,16.8,16.6,16.4,16.1,15.7,15.3,14.9,0.0
253,Virgin Islands (U.S.),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
254,Vietnam,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26.9,26.2,25.5,24.8,24.2,23.5,22.9,22.3,21.7,0.0
255,Vanuatu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,28.2,28.2,28.4,28.5,28.6,28.6,28.4,28.1,27.5,0.0
256,West Bank and Gaza,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.2,24.7,24.2,23.8,23.3,22.8,22.3,21.7,21.1,0.0
258,Samoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18.9,18.8,24.1,18.7,18.6,18.5,18.2,17.9,17.5,0.0
259,"Yemen, Rep.",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,64.7,61.0,57.6,54.2,51.1,48.4,46.0,43.8,41.9,0.0
260,South Africa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,71.3,68.4,63.5,53.8,49.8,47.7,43.4,41.4,40.5,0.0
261,"Congo, Dem. Rep.",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,128.9,124.5,120.1,116.1,112.2,108.5,104.8,101.7,98.3,0.0
262,Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,98.0,93.1,87.4,82.1,78.6,74.4,70.2,66.6,64.0,0.0
263,Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,98.0,95.4,92.9,89.5,85.6,78.5,74.5,72.3,70.7,0.0

In [13]:
target_copy = target_df_final.iloc[:, 1:].copy()

In [14]:
target_copy.columns = range(1950, 2017)

In [15]:
target_copy.interpolate(axis=1, limit_direction='both', method = 'spline', order = 1, limit = 10000, inplace = True)

In [16]:
target_df_final.iloc[:, 1:] = target_copy.values

In [17]:
target_df_final

,Country Name,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,66.079189,66.242535,66.405881,66.569227,66.732574,66.895920,67.059266,67.222612,67.385958,...,74.526756,74.675732,74.818146,74.953537,76.043308,76.206654,76.370001,76.533347,76.696693,76.860039
1,Afghanistan,25.343483,25.928843,26.514204,27.099564,27.684924,28.270285,28.855645,29.441005,30.026366,...,57.833829,58.225024,58.603683,58.970829,61.050465,61.635825,62.221185,62.806546,63.391906,63.977267
2,Angola,31.276143,31.543230,31.810316,32.077403,32.344489,32.611575,32.878662,33.145748,33.412835,...,49.435732,49.847390,50.251024,50.654171,49.593188,49.941265,50.289343,50.637420,50.985497,51.333575
3,Albania,62.088492,62.337358,62.586223,62.835089,63.083955,63.332821,63.581686,63.830552,64.079418,...,76.470293,76.652073,76.840366,77.036951,77.269299,77.518165,77.767030,78.015896,78.264762,78.513627
4,United Arab Emirates,50.418938,50.965479,51.512020,52.058562,52.605103,53.151644,53.698185,54.244726,54.791268,...,76.111171,76.307756,76.494780,76.675244,78.208385,78.532944,78.857502,79.182061,79.506619,79.831178
5,Argentina,62.522313,62.745562,62.968811,63.192060,63.415309,63.638558,63.861807,64.085056,64.308305,...,75.009049,75.166268,75.324561,75.484976,76.140502,76.363751,76.587000,76.810249,77.033498,77.256747
6,Armenia,66.142346,66.292107,66.441868,66.591629,66.741390,66.891151,67.040912,67.190673,67.340434,...,73.764659,73.945000,74.095829,74.226341,74.242223,74.537270,74.832316,75.127363,75.422409,75.717456
7,Antigua and Barbuda,60.271160,60.534626,60.798091,61.061556,61.325022,61.588487,61.851952,62.115418,62.378883,...,74.803220,74.979171,75.147024,75.308780,76.342546,76.606012,76.869477,77.132942,77.396408,77.659873
8,Australia,66.799305,67.049667,67.300029,67.550392,67.800754,68.051117,68.301479,68.551842,68.802204,...,81.292683,81.395122,81.543902,81.695122,82.071413,82.321775,82.572137,82.822500,83.072862,83.323225
9,Austria,65.465348,65.715528,65.965707,66.215887,66.466067,66.716246,66.966426,67.216606,67.466785,...,80.180488,80.431707,80.331707,80.580488,80.726309,80.976488,81.226668,81.476848,81.727028,81.977207
10,Azerbaijan,61.631181,61.731393,61.831605,61.931817,62.032029,62.132241,62.232453,62.332665,62.432877,...,69.756512,70.063951,70.293683,70.451317,69.227565,69.412266,69.596967,69.781667,69.966368,70.151069
11,Burundi,39.105532,39.350848,39.596164,39.841480,40.086796,40.332112,40.577428,40.822744,41.068060,...,53.456073,53.891024,54.351220,54.829195,54.069805,54.315121,54.560437,54.805753,55.051068,55.296384
12,Belgium,67.039116,67.255966,67.472816,67.689666,67.906515,68.123365,68.340215,68.557065,68.773915,...,79.782927,79.680488,79.982927,80.182927,80.266961,80.483811,80.700661,80.917510,81.134360,81.351210
13,Benin,33.900831,34.340176,34.779521,35.218866,35.658211,36.097556,36.536901,36.976246,37.415591,...,57.867390,58.204512,58.491268,58.729707,60.700876,61.140221,61.579566,62.018911,62.458256,62.897601
14,Burkina Faso,29.285444,29.804157,30.322869,30.841582,31.360294,31.879007,32.397719,32.916432,33.435144,...,55.188805,55.902293,56.524976,57.051390,55.980184,56.352869,56.725555,57.098241,57.470926,57.843612
15,Bangladesh,41.180747,41.557442,41.934138,42.310833,42.687529,43.064225,43.440920,43.817616,44.194312,...,68.859976,69.277854,69.683780,70.080293,71.192903,71.787815,72.382727,72.977640,73.572552,74.167464
16,Bulgaria,70.006138,70.046152,70.086165,70.126178,70.166192,70.206205,70.246219,70.286232,70.326246,...,72.663415,72.963415,73.412195,73.512195,72.446957,72.486970,72.526984,72.566997,72.607011,72.647024
17,Bahrain,49.490307,50.167628,50.844950,51.522272,52.199593,52.876915,53.554236,54.231558,54.908880,...,75.707756,75.847512,75.987780,76.127561,77.435601,77.679301,77.923001,78.166701,78.410401,78.654101
18,"Bahamas, The",61.353284,61.577795,61.802306,62.026816,62.251327,62.475837,62.700348,62.924859,63.149369,...,74.059463,74.247439,74.423902,74.592390,75.048431,75.272942,75.497452,75.721963,75.946473,76.170984
19,Bosnia and Herzegovina,59.790416,60.092973,60.395531,60.698088,61.000645,61.303203,61.605760,61.908317,62.210875,...,75.371488,75.511976,75.657366,75.807683,76.504648,76.737534,76.970421,77.203308,77.436194,77.669081
20,Belarus,69.977553,69.969381,69.961209,69.953036,69.944864,69.936692,69.928520,69.920347,69.912175,...,70.203415,70.456098,70.407317,70.404878,69.479046,69.470874,69.462702,69.454530,69.446357,69.438185
21,Belize,59.361585,59.665109,59.968633,60.272156,60.575680,60.879204,61.182727,61.486251,61.789775,...,69.452000,69.594220,69.703073,69.782049,69.471639,69.438967,69.406295,69.373623,69.340951,69.308279
22,Bermuda,65.181139,65.424323,65.667507,65.910691,66.153875,66.397058,66.640242,66.883426,67.126610,...,78.934146,79.236585,79.388439,79.288537,80.015360,80.258544,80.501728,80.744912,80.988096,81.231280
23,Bolivia,35.660050,36.158187,36.656324,37.154462,37.652599,38.150737,38.648874,39.147011,39.645149,...,64.694122,65.273805,65.848000,66.407756,66.046429,66.544567,67.042704,67.540841,68.038979,68.537116
24,Brazil,51.171502,51.540909,51.910316,52.279723,52.649130,53.018537,53.387944,53.757351,54.126758,...,72.414829,72.695415,72.978024,73.264146,73.705328,74.074735,74.444142,74.813549,75.182956,75.552363
25,Barbados,59.907392,60.175038,60.442683,60.710329,60.977975,61.245621,61.513266,61.780912,62.048558,...,74.356415,74.519195,74.682488,74.845293,76.233783,76.501428,76.769074,77.036720,77.304366,77.572011
26,Brunei Darussalam,61.347666,61.628605,61.909543,62.190482,62.471421,62.752359,63.033298,63.314237,63.595175,...,76.675561,76.956756,77.268293,77.598268,78.484921,78.765860,79.046799,79.327737,79.608676,79.889614
27,Bhutan,22.320382,23.082576,23.844770,24.606964,25.369158,26.131352,26.893546,27.655740,28.417934,...,66.293098,66.885024,67.416659,67.892415,68.814218,69.576412,70.338606,71.100800,71.862994,72.625188
28,Botswana,44.512072,45.035532,45.558993,46.082453,46.605914,47.129374,47.652835,48.176296,48.699756,...,59.074561,60.958585,62.417098,63.402293,64.805901,66.594284,68.382667,70.171049,71.959432,73.747815
29,Central African Republic,32.205613,32.707105,33.208596,33.710088,34.211580,34.713072,35.214563,35.716055,36.217547,...,45.687390,46.284000,46.934976,47.625317,45.175253,45.102941,45.030630,44.958318,44.886006,44.813694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,Seychelles,63.944382,64.099597,64.254813,64.410028,64.565243,64.720459,64.875674,65.030889,65.186105,...,73.192683,73.163415,73.034146,73.197561,73.412517,73.567732,73.722948,73.878163,74.033378,74.188594
173,Syrian Arab Republic,48.902799,49.432944,49.963090,50.493236,51.023381,51.553527,52.083673,52.613818,53.143964,...,74.246073,73.797244,73.120415,72.307439,76.339505,76.673563,77.007622,77.341680,77.675739,78.009797
174,Chad,37.284834,37.500968,37.717101,37.933235,38.149369,38.365503,38.581636,38.797770,39.013904,...,48.559220,48.951585,49.393171,49.862073,50.468993,50.685126,50.901260,51.117394,51.333528,51.549661
175,Togo,37.290399,37.759230,38.228061,38.696893,39.165724,39.634555,40.103386,40.572217,41.041048,...,55.433439,56.005902,56.630610,57.281561,55.932904,56.003487,56.074071,56.144654,56.215238,56.285821
176,Thailand,51.401377,51.830266,52.259154,52.688042,53.116930,53.545818,53.974706,54.403594,54.832482,...,72.874439,73.188439,73.461732,73.694366,75.089047,75.418955,75.748863,76.078771,76.408679,76.738587
177,Tajikistan,56.072152,56.249545,56.426938,56.604332,56.781725,56.959118,57.136512,57.313905,57.491298,...,67.207488,67.714585,68.170537,68.563390,66.893143,67.070536,67.247929,67.425322,67.602716,67.780109
178,Turkmenistan,54.445436,54.637231,54.829027,55.020823,55.212618,55.404414,55.596210,55.788005,55.979801,...,64.638829,64.756073,64.883537,65.021244,66.144972,66.336768,66.528564,66.720360,66.912155,67.103951
179,Timor-Leste,28.112387,28.686933,29.261479,29.836024,30.410570,30.985116,31.559662,32.134208,32.708754,...,65.824195,66.457829,66.946683,67.308390,69.981657,71.004506,72.027355,73.050204,74.073053,75.095902
180,Tonga,60.873560,61.075836,61.278113,61.480389,61.682665,61.884941,62.087217,62.289493,62.491770,...,71.737000,71.883195,72.031756,72.182610,73.212406,73.414682,73.616958,73.819234,74.021511,74.223787
181,Trinidad and Tobago,63.070720,63.185894,63.301067,63.416241,63.531414,63.646588,63.761762,63.876935,63.992109,...,69.259659,69.428927,69.610585,69.797561,70.096308,70.211482,70.326655,70.441829,70.557002,70.672176
182,Tunisia,33.159961,34.086232,35.012504,35.938776,36.865048,37.791319,38.717591,39.643863,40.570134,...,74.202439,74.302439,74.451220,74.602439,77.172107,77.598761,78.025416,78.452071,78.878725,79.305380
183,Turkey,40.767539,41.347516,41.927493,42.507470,43.087447,43.667424,44.247401,44.827378,45.407356,...,73.177073,73.500756,73.803220,74.090927,76.146144,76.726121,77.306098,77.886075,78.466052,79.046029
184,Tanzania,42.169224,42.401863,42.634501,42.867140,43.099779,43.332418,43.565057,43.797695,44.030334,...,58.077780,59.314707,60.509512,61.625610,60.108278,60.846067,61.583857,62.321646,63.059435,63.797224
185,Uganda,43.218204,43.471770,43.725336,43.978902,44.232469,44.486035,44.739601,44.993167,45.246734,...,53.654146,54.461976,55.182098,55.836659,55.617078,56.395669,57.174259,57.952850,58.731440,59.510031
186,Ukraine,70.444711,70.406716,70.368721,70.330726,70.292731,70.254736,70.216741,70.178745,70.140750,...,68.222195,68.251463,69.190000,70.265366,68.127010,68.089014,68.051019,68.013024,67.975029,67.937034
187,Uruguay,65.181605,65.367291,65.552977,65.738663,65.924349,66.110035,66.295720,66.481406,66.667092,...,75.951024,76.101073,76.248585,76.394610,76.508440,76.694126,76.879811,77.065497,77.251183,77.436869
188,United States,67.755780,67.937567,68.119354,68.301141,68.482928,68.664715,68.846503,69.028290,69.210077,...,77.987805,78.039024,78.390244,78.541463,78.844788,79.026575,79.208362,79.390150,79.571937,79.753724
189,Uzbekistan,59.773584,59.924897,60.076210,60.227524,60.378837,60.530150,60.681464,60.832777,60.984090,...,67.531220,67.634195,67.744561,67.861293,69.003696,69.155009,69.306322,69.457636,69.608949,69.760262
190,St. Vincent and the Grenadines,59.551386,59.791033,60.030680,60.270327,60.509975,60.749622,60.989269,61.228916,61.468563,...,71.699415,71.931732,72.150073,72.346390,73.495493,73.708165,73.920837,74.133510,74.346182,74.558854
191,"Venezuela, RB",59.211670,59.473785,59.735900,59.998016,60.260131,60.522246,60.784361,61.046476,61.308591,...,73.388902,73.476244,73.568000,73.671610,75.200692,75.462807,75.724922,75.987037,76.249152,76.511267
192,Virgin Islands (U.S.),61.503409,61.820909,62.138408,62.455908,62.773408,63.090908,63.408408,63.725907,64.043407,...,78.824390,78.924390,79.073171,79.173171,80.870896,81.188395,81.505895,81.823395,82.140895,82.458395
193,Vietnam,59.269318,59.354899,59.440479,59.526060,59.611641,59.697222,59.782802,59.868383,59.953964,...,74.483854,74.653098,74.822610,74.990366,75.825038,76.085449,76.345859,76.606270,76.866681,77.127092
194,Vanuatu,42.941612,43.432911,43.924211,44.415510,44.906809,45.398108,45.889408,46.380707,46.872006,...,69.948732,70.254756,70.555829,70.849951,72.910866,73.402166,73.893465,74.384764,74.876063,75.367363
195,West Bank and Gaza,60.578969,60.777284,60.975599,61.173913,61.372228,61.570543,61.768858,61.967173,62.165488,...,71.747049,71.894951,72.051098,72.214927,72.676177,72.874492,73.072807,73.271122,73.469436,73.667751
196,Samoa,45.823019,46.289704,46.756389,47.223074,47.689760,48.156445,48.623130,49.089815,49.556501,...,71.560780,71.844293,72.130683,72.417000,74.290818,74.757503,75.224188,75.690873,76.157559,76.624244
197,"Yemen, Rep.",25.758887,26.560016,27.361145,28.162274,28.963403,29.764532,30.565661,31.366790,32.167919,...,61.954805,62.211366,62.485341,62.768732,65.117873,65.538606,65.959340,66.380074,66.800807,67.221541
198,South Africa,43.807195,44.267058,44.726920,45.186783,45.646645,46.106507,46.566370,47.026232,47.486095,...,51.996512,52.636024,53.467098,54.390756,51.232140,50.873832,50.515524,50.157216,49.798908,49.440600
199,"Congo, Dem. Rep.",38.095839,38.367101,38.638363,38.909625,39.180887,39.452149,39.723411,39.994673,40.265934,...,55.064415,55.724000,56.337073,56.896146,54.642817,54.914079,55.185341,55.456603,55.727864,55.999126
200,Zambia,40.117310,40.589609,41.061908,41.534207,42.006506,42.478805,42.951104,43.423403,43.895703,...,52.477146,53.905634,55.214171,56.383854,56.094829,57.197570,58.300311,59.403052,60.505793,61.608534
201,Zimbabwe,47.061630,47.471173,47.880716,48.290259,48.699802,49.109345,49.518888,49.928431,50.337973,...,44.177756,45.804488,47.624659,49.574659,47.473404,48.315913,49.158422,50.000932,50.843441,51.685950

In [18]:
input_df_final.head()

,Country Name,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,113.2,110.4,107.6,105.0,102.3,99.5,96.7,93.9,91.1,0.0
3,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,196.4,192.0,187.3,182.5,177.3,172.2,167.1,162.2,156.9,0.0
4,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18.7,17.9,17.3,16.6,16.0,15.5,14.9,14.4,14.0,0.0
6,United Arab Emirates,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.4,9.1,8.8,8.5,8.2,7.8,7.4,7.1,6.8,0.0

In [19]:
np.sum(input_df_final.isnull())

Country Name    0
1950            0
1951            0
1952            0
1953            0
1954            0
1955            0
1956            0
1957            0
1958            0
1959            0
1960            0
1961            0
1962            0
1963            0
1964            0
1965            0
1966            0
1967            0
1968            0
1969            0
1970            0
1971            0
1972            0
1973            0
1974            0
1975            0
1976            0
1977            0
1978            0
               ..
1987            0
1988            0
1989            0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
2012            0
2013            0
2014            0
2015            0
2016            0
dtype: int64

In [25]:
target_data_long = pd.melt(target_df_final, id_vars=['Country Name'], var_name = 'Year', value_name='LifeExp')
input_data_long = pd.melt(input_df_final, id_vars=['Country Name'], var_name = 'Year', value_name='U5_MORT')

In [71]:
target_data_long.loc[target_data_long['Year'] == '1961']

                        Country Name  Year    LifeExp
2222                           Aruba  1961  65.988024
2223                     Afghanistan  1961  32.777439
2224                          Angola  1961  33.386220
2225                         Albania  1961  63.273463
2226            United Arab Emirates  1961  53.286561
2227                       Argentina  1961  65.338512
2228                         Armenia  1961  66.284390
2229             Antigua and Barbuda  1961  62.195415
2230                       Australia  1961  70.973171
2231                         Austria  1961  69.577317
2232                      Azerbaijan  1961  61.239171
2233                         Burundi  1961  41.545463
2234                         Belgium  1961  70.520976
2235                           Benin  1961  37.731195
2236                    Burkina Faso  1961  34.938634
2237                      Bangladesh  1961  46.457927
2238                        Bulgaria  1961  70.195610
2239                         Bahrain  1961  53.458512
2240                    Bahamas, The  1961  63.072512
2241          Bosnia and Herzegovina  1961  60.941585
2242                         Belarus  1961  68.212659
2243                          Belize  1961  60.512780
2244                         Bermuda  1961  67.856162
2245                         Bolivia  1961  42.433439
2246                          Brazil  1961  54.718707
2247                        Barbados  1961  61.215098
2248               Brunei Darussalam  1961  63.048951
2249                          Bhutan  1961  32.731024
2250                        Botswana  1961  50.907634
2251        Central African Republic  1961  36.895707
...                              ...   ...        ...
2394                      Seychelles  1961  65.651751
2395            Syrian Arab Republic  1961  53.312561
2396                            Chad  1961  38.273439
2397                            Togo  1961  40.916488
2398                        Thailand  1961  55.232732
2399                      Tajikistan  1961  56.562610
2400                    Turkmenistan  1961  54.871195
2401                     Timor-Leste  1961  34.237561
2402                           Tonga  1961  61.732707
2403             Trinidad and Tobago  1961  63.253756
2404                         Tunisia  1961  42.645512
2405                          Turkey  1961  46.104488
2406                        Tanzania  1961  43.907293
2407                          Uganda  1961  44.560024
2408                         Ukraine  1961  68.763854
2409                         Uruguay  1961  68.112780
2410                   United States  1961  70.270732
2411                      Uzbekistan  1961  59.297537
2412  St. Vincent and the Grenadines  1961  58.809683
2413                   Venezuela, RB  1961  59.862561
2414           Virgin Islands (U.S.)  1961  64.101561
2415                         Vietnam  1961  59.744195
2416                         Vanuatu  1961  47.088098
2417              West Bank and Gaza  1961  62.760433
2418                           Samoa  1961  50.469512
2419                     Yemen, Rep.  1961  34.473244
2420                    South Africa  1961  49.429805
2421                Congo, Dem. Rep.  1961  41.233537
2422                          Zambia  1961  45.487512
2423                        Zimbabwe  1961  51.914951

[202 rows x 3 columns]

In [27]:
target_data_long.tail()

           Country Name  Year    LifeExp
13529       Yemen, Rep.  2016  67.221541
13530      South Africa  2016  49.440600
13531  Congo, Dem. Rep.  2016  55.999126
13532            Zambia  2016  61.608534
13533          Zimbabwe  2016  51.685950

In [28]:
input_data_long.head()

           Country Name  Year  U5_MORT
0                 Aruba  1950      0.0
1           Afghanistan  1950      0.0
2                Angola  1950      0.0
3               Albania  1950      0.0
4  United Arab Emirates  1950      0.0

In [29]:
input_data_long.tail()

           Country Name  Year  U5_MORT
13529       Yemen, Rep.  2016      0.0
13530      South Africa  2016      0.0
13531  Congo, Dem. Rep.  2016      0.0
13532            Zambia  2016      0.0
13533          Zimbabwe  2016      0.0

In [30]:
np.sum(target_data_long.isnull())

Country Name    0
Year            0
LifeExp         0
dtype: int64

In [31]:
np.sum(input_data_long.isnull())

Country Name    0
Year            0
U5_MORT         0
dtype: int64

In [32]:
X = input_data_long[['Country Name', 'Year', 'U5_MORT']]
X.ix[:,'Year'] = pd.to_numeric(X.ix[:,'Year'])
Y = target_data_long[['LifeExp']]

In [33]:
X.head()

           Country Name  Year  U5_MORT
0                 Aruba  1950      0.0
1           Afghanistan  1950      0.0
2                Angola  1950      0.0
3               Albania  1950      0.0
4  United Arab Emirates  1950      0.0

In [34]:
X.dtypes

Country Name     object
Year              int64
U5_MORT         float64
dtype: object

In [35]:
Y.head()

     LifeExp
0  66.079189
1  25.343483
2  31.276143
3  62.088492
4  50.418938

In [36]:
VALIDATION_long = pd.melt(VALIDATION, id_vars=['Country Name'], var_name = 'Year', value_name='LifeExp')

In [37]:
VALIDATION.head()

           Country Name       1960       2011       2012       2013       2014
0                 Aruba  65.569366  75.081390  75.205756  75.328659  75.451098
2           Afghanistan  32.328512  59.327951  59.679610  60.028268  60.374463
3                Angola  32.984829  51.059317  51.464000  51.866171  52.266878
4               Albania  62.254366  77.240585  77.443976  77.640463  77.830463
6  United Arab Emirates  52.243220  76.851195  77.024146  77.195634  77.368171

In [38]:
VALIDATION_long

                       Country Name  Year    LifeExp
0                             Aruba  1960  65.569366
1                       Afghanistan  1960  32.328512
2                            Angola  1960  32.984829
3                           Albania  1960  62.254366
4              United Arab Emirates  1960  52.243220
5                         Argentina  1960  65.215537
6                           Armenia  1960  65.863463
7               Antigua and Barbuda  1960  61.782732
8                         Australia  1960  70.817073
9                           Austria  1960  68.585610
10                       Azerbaijan  1960  60.836244
11                          Burundi  1960  41.236049
12                          Belgium  1960  69.701951
13                            Benin  1960  37.278268
14                     Burkina Faso  1960  34.477902
15                       Bangladesh  1960  45.829317
16                         Bulgaria  1960  69.247561
17                          Bahrain  1960  52.089366
18                     Bahamas, The  1960  62.729049
19           Bosnia and Herzegovina  1960  60.276220
20                          Belarus  1960  67.708098
21                           Belize  1960  59.961366
22                          Bolivia  1960  42.118317
23                           Brazil  1960  54.205463
24                         Barbados  1960  60.738049
25                Brunei Darussalam  1960  62.500366
26                           Bhutan  1960  32.359366
27                         Botswana  1960  50.547732
28         Central African Republic  1960  36.482634
29                           Canada  1960  71.133171
..                              ...   ...        ...
910                          Sweden  2014  81.956098
911                       Swaziland  2014  48.934732
912            Syrian Arab Republic  2014  70.071024
913                            Chad  2014  51.555805
914                            Togo  2014  59.655805
915                        Thailand  2014  74.422024
916                      Tajikistan  2014  69.597976
917                    Turkmenistan  2014  65.598537
918                     Timor-Leste  2014  68.259146
919                           Tonga  2014  72.792195
920             Trinidad and Tobago  2014  70.440561
921                         Tunisia  2014  74.143902
922                          Turkey  2014  75.163512
923                        Tanzania  2014  64.943902
924                          Uganda  2014  58.466415
925                         Ukraine  2014  71.186585
926                         Uruguay  2014  76.986146
927                   United States  2014  78.941463
928                      Uzbekistan  2014  68.339024
929  St. Vincent and the Grenadines  2014  72.936854
930                   Venezuela, RB  2014  74.236195
931           Virgin Islands (U.S.)  2014  79.773171
932                         Vietnam  2014  75.629122
933                         Vanuatu  2014  71.918317
934                           Samoa  2014  73.511829
935                     Yemen, Rep.  2014  63.818195
936                    South Africa  2014  57.182122
937                Congo, Dem. Rep.  2014  58.659195
938                          Zambia  2014  60.047049
939                        Zimbabwe  2014  57.498317

[940 rows x 3 columns]

In [39]:
X

                         Country Name  Year  U5_MORT
0                               Aruba  1950      0.0
1                         Afghanistan  1950      0.0
2                              Angola  1950      0.0
3                             Albania  1950      0.0
4                United Arab Emirates  1950      0.0
5                           Argentina  1950      0.0
6                             Armenia  1950      0.0
7                 Antigua and Barbuda  1950      0.0
8                           Australia  1950      0.0
9                             Austria  1950      0.0
10                         Azerbaijan  1950      0.0
11                            Burundi  1950      0.0
12                            Belgium  1950      0.0
13                              Benin  1950      0.0
14                       Burkina Faso  1950      0.0
15                         Bangladesh  1950      0.0
16                           Bulgaria  1950      0.0
17                            Bahrain  1950      0.0
18                       Bahamas, The  1950      0.0
19             Bosnia and Herzegovina  1950      0.0
20                            Belarus  1950      0.0
21                             Belize  1950      0.0
22                            Bermuda  1950      0.0
23                            Bolivia  1950      0.0
24                             Brazil  1950      0.0
25                           Barbados  1950      0.0
26                  Brunei Darussalam  1950      0.0
27                             Bhutan  1950      0.0
28                           Botswana  1950      0.0
29           Central African Republic  1950      0.0
...                               ...   ...      ...
13504                      Seychelles  2016      0.0
13505            Syrian Arab Republic  2016      0.0
13506                            Chad  2016      0.0
13507                            Togo  2016      0.0
13508                        Thailand  2016      0.0
13509                      Tajikistan  2016      0.0
13510                    Turkmenistan  2016      0.0
13511                     Timor-Leste  2016      0.0
13512                           Tonga  2016      0.0
13513             Trinidad and Tobago  2016      0.0
13514                         Tunisia  2016      0.0
13515                          Turkey  2016      0.0
13516                        Tanzania  2016      0.0
13517                          Uganda  2016      0.0
13518                         Ukraine  2016      0.0
13519                         Uruguay  2016      0.0
13520                   United States  2016      0.0
13521                      Uzbekistan  2016      0.0
13522  St. Vincent and the Grenadines  2016      0.0
13523                   Venezuela, RB  2016      0.0
13524           Virgin Islands (U.S.)  2016      0.0
13525                         Vietnam  2016      0.0
13526                         Vanuatu  2016      0.0
13527              West Bank and Gaza  2016      0.0
13528                           Samoa  2016      0.0
13529                     Yemen, Rep.  2016      0.0
13530                    South Africa  2016      0.0
13531                Congo, Dem. Rep.  2016      0.0
13532                          Zambia  2016      0.0
13533                        Zimbabwe  2016      0.0

[13534 rows x 3 columns]

In [40]:
X = pd.get_dummies(X)

In [41]:
X.head()

,Year,U5_MORT,Country Name_Afghanistan,Country Name_Albania,Country Name_Algeria,Country Name_Angola,Country Name_Antigua and Barbuda,Country Name_Argentina,Country Name_Armenia,Country Name_Aruba,...,Country Name_Uruguay,Country Name_Uzbekistan,Country Name_Vanuatu,"Country Name_Venezuela, RB",Country Name_Vietnam,Country Name_Virgin Islands (U.S.),Country Name_West Bank and Gaza,"Country Name_Yemen, Rep.",Country Name_Zambia,Country Name_Zimbabwe
0,1950,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1950,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1950,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1950,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1950,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
VALIDATION_long.ix[:,'Year'] = pd.to_numeric(VALIDATION_long.ix[:,'Year'])

In [44]:
X_test_df = pd.concat([X.loc[(X['Country Name_%s' % (row['Country Name'])]==1) & (X['Year']==row['Year'])] for index, row in VALIDATION_long.iterrows()])
Y_test_df = VALIDATION_long['LifeExp']

In [45]:
X_test_df

,Year,U5_MORT,Country Name_Afghanistan,Country Name_Albania,Country Name_Algeria,Country Name_Angola,Country Name_Antigua and Barbuda,Country Name_Argentina,Country Name_Armenia,Country Name_Aruba,...,Country Name_Uruguay,Country Name_Uzbekistan,Country Name_Vanuatu,"Country Name_Venezuela, RB",Country Name_Vietnam,Country Name_Virgin Islands (U.S.),Country Name_West Bank and Gaza,"Country Name_Yemen, Rep.",Country Name_Zambia,Country Name_Zimbabwe
2020,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021,1960,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022,1960,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023,1960,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024,1960,204.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025,1960,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2026,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2027,1960,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2028,1960,24.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2029,1960,42.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2030,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2031,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2032,1960,33.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2033,1960,314.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2034,1960,347.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2035,1960,264.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2036,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2037,1960,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2038,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2039,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2040,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2041,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2043,1960,287.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2044,1960,171.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2045,1960,83.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2046,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2047,1960,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2048,1960,169.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2049,1960,283.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2050,1960,32.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13097,2014,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13098,2014,62.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13101,2014,14.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13102,2014,142.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13103,2014,80.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13104,2014,12.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13105,2014,46.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13106,2014,53.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13107,2014,54.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13108,2014,17.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13109,2014,20.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13110,2014,14.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13111,2014,14.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13112,2014,50.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13113,2014,56.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13114,2014,9.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13115,2014,10.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13116,2014,6.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13117,2014,40.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13118,2014,18.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13119,2014,15.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13120,2014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13121,2014,22.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
13122,2014,28.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13124,2014,17.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13125,2014,43.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13126,2014,41.4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13127,2014,101.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13128,2014,66.6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13129,2014,72.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### Linear Regression

In [46]:
from sklearn import linear_model
linearRegression = linear_model.LinearRegression()

In [47]:
linearRegression.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [48]:
predictions = linearRegression.predict(X)

In [49]:
print "MSE is" , sk.metrics.mean_squared_error(Y, predictions)

MSE is 12.9973206218

In [50]:
predictions = linearRegression.predict(X_test_df)
print "MSE is" , sk.metrics.mean_squared_error(Y_test_df, predictions)

MSE is 16.5321316195

### Decision Trees

In [51]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, Y)
tree = DecisionTreeRegressor(max_depth = 230, random_state=0)
tree.fit(X_train, y_train)
predicted_y = tree.predict(X_train)
predicted_y_test = tree.predict(X_test)
print("MSE on training set: {:.3f}".format(sk.metrics.mean_squared_error(y_train, predicted_y)))
print("MSE on test set: {:.3f}".format(sk.metrics.mean_squared_error(y_test, predicted_y_test)))
print("R^2 on training set: {:.3f}".format(tree.score(X_train, y_train))) 
print("R^2 on test set: {:.3f}".format(tree.score(X_test, y_test)))

MSE on training set: 0.000
MSE on test set: 4.678
R^2 on training set: 1.000
R^2 on test set: 0.970

In [52]:
# depth_list = range(200,240)
# MSE_list = []

In [53]:
# kf = KFold(len(Y), n_folds=10, shuffle = True)

In [54]:
# for depth in depth_list:
    
#     MSE_depth_CV =[]

#     for train_index, test_index in kf:
#         X_train_CV, X_test_CV = X.iloc[train_index,:], X.iloc[test_index,:]
#         Y_train_CV, Y_test_CV = Y.iloc[train_index,:], Y.iloc[test_index,:]
#         regressor = DecisionTreeRegressor(max_depth = depth) 
#         regressor.fit(X_train_CV, Y_train_CV) 
#         predicted_y = regressor.predict(X_test_CV)
#         MSE = sk.metrics.mean_squared_error(Y_test_CV, predicted_y)
#         MSE_depth_CV.append(MSE)
    
#     print depth, "k-fold CV is", np.mean(MSE_depth_CV)

In [57]:
regressor = DecisionTreeRegressor(max_depth = 230) 
regressor.fit(X, Y) 
predicted_y = regressor.predict(X)
MSE = sk.metrics.mean_squared_error(Y, predicted_y)

print "MSE is", MSE

MSE is 3.68199406182e-11

In [58]:
predictions = regressor.predict(X_test_df)
print "MSE is" , sk.metrics.mean_squared_error(Y_test_df, predictions)

MSE is 3.52230844293

### Random Forests

In [61]:
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(X, Y)
forest = RandomForestRegressor()

forest.fit(X_train, y_train.values.ravel())

predicted_y = forest.predict(X_train)
predicted_y_test = forest.predict(X_test)
print("MSE on training set: {:.3f}".format(sk.metrics.mean_squared_error(y_train, predicted_y)))
print("MSE on test set: {:.3f}".format(sk.metrics.mean_squared_error(y_test, predicted_y_test)))

print("R^2 on training set: {:.3f}".format(forest.score(X_train, y_train))) 
print("R^2 on test set: {:.3f}".format(forest.score(X_test, y_test)))

MSE on training set: 0.860
MSE on test set: 4.037
R^2 on training set: 0.994
R^2 on test set: 0.974

In [62]:
regressor = RandomForestRegressor() 
regressor.fit(X, Y.values.ravel()) 
predicted_y = regressor.predict(X)
MSE = sk.metrics.mean_squared_error(Y, predicted_y)

print "MSE is", MSE

MSE is 0.492624612422

In [63]:
predictions = regressor.predict(X_test_df)
print "MSE is" , sk.metrics.mean_squared_error(Y_test_df, predictions)

MSE is 3.13236307908

### Gradient Boosting Machines

In [64]:
from sklearn.ensemble import GradientBoostingRegressor
X_train, X_test, y_train, y_test = train_test_split(
        X,Y)
gbrt = GradientBoostingRegressor(max_depth=40)
gbrt.fit(X_train, y_train.values.ravel())

predicted_y = gbrt.predict(X_train)
predicted_y_test = gbrt.predict(X_test)
print("MSE on training set: {:.3f}".format(sk.metrics.mean_squared_error(y_train, predicted_y)))
print("MSE on test set: {:.3f}".format(sk.metrics.mean_squared_error(y_test, predicted_y_test)))

MSE on training set: 0.109
MSE on test set: 3.073

In [65]:
regressor = GradientBoostingRegressor(max_depth=40)
regressor.fit(X, Y.values.ravel()) 
predicted_y = regressor.predict(X)
MSE = sk.metrics.mean_squared_error(Y, predicted_y)

print "MSE is", MSE

MSE is 0.123507341936

In [66]:
predictions = regressor.predict(X_test_df)
print "MSE is" , sk.metrics.mean_squared_error(Y_test_df, predictions)

MSE is 3.45270026106

### Neural Networks

In [82]:
# from sklearn.preprocessing import StandardScaler
# from sklearn.neural_network import MLPRegressor
# scaler = StandardScaler()

# X_scaled = scaler.fit_transform(X)

ImportError: cannot import name MLPRegressor

In [ ]:
# mlp = MLPReg(max_iter=1000, random_state=0)
# mlp.fit(X_train_scaled, y_train)
# print("Accuracy on training set: {:.3f}".format( mlp.score(X_train_scaled, y_train)))
# print("Accuracy on test set: {:.3f}".format(mlp.score(X_test_scaled, y_test)))

In [ ]:
# X = input_data_long[['Year', 'GDP']]
# Y = target_data_long[['LifeExp']]

In [323]:
# X = pd.get_dummies(X)
# X.ix[:,'Year'] = pd.to_numeric(X.ix[:,'Year']).values

In [325]:
# X.head()

   Year        GDP
0  1961   1.245086
1  1961   8.444163
2  1961   2.800000
3  1961   5.745635
4  1961  16.526856

In [326]:
# X.dtypes

Year      int64
GDP     float64
dtype: object

In [327]:
# linearRegression.fit(X,Y)
# predictions = linearRegression.predict(X)
# print "MSE is" , sk.metrics.mean_squared_error(Y, predictions)

MSE is 112.200475408

In [328]:
# print linearRegression.coef_

[[ 0.28348918 -0.05335729]]

In [491]:
# print("scikit-learn version: {}".format(sk.__version__))

scikit-learn version: 0.17.1

### AdaBoost Regressor

     LifeExp
0  65.988024
1  32.777439
2  33.386220
3  63.273463
4  53.286561

In [141]:
from sklearn.ensemble import AdaBoostRegressor
rate = [0.1]    # Learning rate; default is 1.0

for r in rate:
        regressor = AdaBoostRegressor() 
        regressor.fit(X, Y.values.ravel())
        predictions = regressor.predict(X)
        print "MSE with learning rate, %s is" % (r) , sk.metrics.mean_squared_error(Y, predictions) 
        print predictions
        print Y

MSE with learning rate, 0.1 is 116.370505845
[ 55.92313653  55.7170374   55.83168702 ...,  66.14306474  66.14306474
  63.35901665]
         LifeExp
0      65.988024
1      32.777439
2      33.386220
3      63.273463
4      53.286561
5      65.338512
6      66.284390
7      62.195415
8      70.973171
9      69.577317
10     61.239171
11     41.545463
12     70.520976
13     37.731195
14     34.938634
15     46.457927
16     70.195610
17     53.458512
18     63.072512
19     60.941585
20     68.212659
21     60.512780
22     68.897805
23     42.433439
24     54.718707
25     61.215098
26     63.048951
27     32.731024
28     50.907634
29     36.895707
...          ...
10070  73.197561
10071  72.307439
10072  49.862073
10073  57.281561
10074  73.694366
10075  68.563390
10076  65.021244
10077  67.308390
10078  72.182610
10079  69.797561
10080  74.602439
10081  74.090927
10082  61.625610
10083  55.836659
10084  70.265366
10085  76.394610
10086  78.541463
10087  67.861293
10088  72.346390
10089  73.671610
10090  79.173171
10091  74.990366
10092  70.849951
10093  72.214927
10094  72.417000
10095  62.768732
10096  54.390756
10097  56.896146
10098  56.383854
10099  49.574659

[10100 rows x 1 columns]

In [152]:
regressor = RandomForestRegressor() 
regressor.fit(X, Y.values.ravel()) 
predictions = regressor.predict(X)
MSE = sk.metrics.mean_squared_error(Y, predictions)

print "MSE is", MSE

MSE is 0.756749663491

In [37]:
X.head()

,Year,GDP,Country Name_Afghanistan,Country Name_Albania,Country Name_Algeria,Country Name_Angola,Country Name_Antigua and Barbuda,Country Name_Argentina,Country Name_Armenia,Country Name_Aruba,...,Country Name_Uruguay,Country Name_Uzbekistan,Country Name_Vanuatu,"Country Name_Venezuela, RB",Country Name_Vietnam,Country Name_Virgin Islands (U.S.),Country Name_West Bank and Gaza,"Country Name_Yemen, Rep.",Country Name_Zambia,Country Name_Zimbabwe
0,1961,1.245086,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1961,8.444163,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1961,2.800000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1961,5.745635,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1961,16.526856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
X_train = df.iloc[:,0:280]
X_test = test_df.iloc[:,0:280]

In [5]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
Y_train = df.iloc[:,280:281]
Y_test = test_df.iloc[:,280]

In [7]:
depth = 5
regressor = DecisionTreeRegressor(max_depth=depth) 
regressor.fit(X_train, Y_train) 
predicted_y = regressor.predict(X_test)

In [8]:
sk.metrics.mean_squared_error(Y_test, predicted_y)

669.66569160245422

In [9]:
depth_list = range(1,20)
MSE_list = []

In [32]:
kf = KFold(len(Y_train), n_folds=10, shuffle = True)

In [27]:
print len(X_train), len(Y_train)

52397 52397

In [33]:
for depth in depth_list:
    
    MSE_depth_CV =[]

    for train_index, test_index in kf:
        X_train_CV, X_test_CV = X_train.iloc[train_index,:], X_train.iloc[test_index,:]
        Y_train_CV, Y_test_CV = Y_train.iloc[train_index,:], Y_train.iloc[test_index,:]
        regressor = DecisionTreeRegressor(max_depth=depth) 
        regressor.fit(X_train_CV, Y_train_CV) 
        predicted_y = regressor.predict(X_test_CV)
        MSE = sk.metrics.mean_squared_error(Y_test_CV, predicted_y)
        MSE_depth_CV.append(MSE)
    
    print depth, "k-fold CV is", np.mean(MSE_depth_CV)

1 k-fold CV is 1094.48596811
2 k-fold CV is 816.360036677
3 k-fold CV is 723.863492028
4 k-fold CV is 694.557312437
5 k-fold CV is 722.944608945
6 k-fold CV is 751.824008538
7 k-fold CV is 770.717029321
8 k-fold CV is 846.656690323
9 k-fold CV is 905.152489712
10 k-fold CV is 966.206092789
11 k-fold CV is 1030.32243944
12 k-fold CV is 1053.06401763
13 k-fold CV is 1099.489705
14 k-fold CV is 1081.98415069
15 k-fold CV is 1121.63768719
16 k-fold CV is 1090.79088817
17 k-fold CV is 1090.04682546
18 k-fold CV is 1082.8004027
19 k-fold CV is 1119.92789668

In [16]:
from StringIO import StringIO
import pydotplus 

my_tree = DecisionTreeRegressor(max_depth=5).fit(X_train_CV, Y_train_CV)
dotfile = StringIO()
sk.tree.export_graphviz(my_tree, out_file=dotfile)
graph = pydotplus.graph_from_dot_data(dotfile.getvalue())
graph.write_pdf("tree.pdf")

True

In [20]:
from IPython.display import IFrame
IFrame("tree.pdf", width=600, height=300)

# Compare to Linear Regression

In [31]:
from sklearn import linear_model

my_tree = DecisionTreeRegressor(max_depth=5).fit(X_train, Y_train)

algo = linear_model.LinearRegression()
algo.fit (X_train, Y_train)
predictions_LR = algo.predict(X_test)
predictions_DT = my_tree.predict(X_test)

MSE_LR = sk.metrics.mean_squared_error(Y_test, predictions_LR)
MSE_DT = sk.metrics.mean_squared_error(Y_test, predictions_DT)

print "MSE on the testing set using Linear Regression is ", MSE_LR
print "MSE on the testing set using the Decision Tree is ", MSE_DT

MSE on the testing set using Linear Regression is  1632.13874612
MSE on the testing set using the Decision Tree is  669.665691602

In [42]:
ridge = linear_model.Ridge (alpha = 0.1)
lasso = linear_model.Lasso(alpha = 0.1)

for model in [ridge, lasso]:
    model.fit(X_train, Y_train)
    predictions = model.predict(X_test)
    
    print "MSE on the testing set using %s is " % (model) , sk.metrics.mean_squared_error(Y_test, predictions)

MSE on the testing set using Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001) is  1631.67077
MSE on the testing set using Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False) is  1644.88424921