In [295]:
from sklearn.tree import DecisionTreeRegressor 
import pandas as pd
from sklearn.cross_validation import KFold
import sklearn as sk
import numpy as np

input_file = 'GDP by country and year.csv'
target_file = 'life expectancy by country and year.csv'
HIV_file = 'HIV rates by country and year.csv'
Income_file = 'Income per capita by country and year.csv'
Internet_file = 'Internet user rates by country and year.csv'
Continent_file = 'Continent.csv'
health_data = 'health_data.csv'

In [296]:
input_df = pd.read_csv(input_file)
target_df = pd.read_csv(target_file)
HIV_df = pd.read_csv(HIV_file)
Income_df = pd.read_csv(Income_file)
Internet_df = pd.read_csv(Internet_file)
Continent_df = pd.read_csv(Continent_file)
health_df = pd.read_csv(health_data)
health_df = health_df.iloc[:-5, :]

In [297]:
# input_df
# health_df.head()

In [298]:
# null_data = target_df[target_df.isnull().any(axis=1)]

In [299]:
# null_data.head()

In [300]:
worldbank_life_exp = pd.read_csv('worldbank_life_exp.csv')
val_set = worldbank_life_exp[['Country Name', '1960', '2011', '2012', '2013', '2014']]
val_set_final = val_set.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
countries = target_df['Country Name'].values
VALIDATION = val_set_final[val_set_final['Country Name'].isin(countries)]
VALIDATION.head()

           Country Name       1960       2011       2012       2013       2014
0                 Aruba  65.569366  75.081390  75.205756  75.328659  75.451098
2           Afghanistan  32.328512  59.327951  59.679610  60.028268  60.374463
3                Angola  32.984829  51.059317  51.464000  51.866171  52.266878
4               Albania  62.254366  77.240585  77.443976  77.640463  77.830463
6  United Arab Emirates  52.243220  76.851195  77.024146  77.195634  77.368171

In [301]:
GDP_growth = pd.read_csv('GDP_Growth.csv')
GDP_growth.drop(GDP_growth.columns[[1,2,3]], axis=1, inplace=True)
GDP_growth.loc[GDP_growth['Country Name'] == 'Korea, Dem. People\x89\xdb\xaas Rep.', 'Country Name'] = 'Korea, Dem. People\xe2\x80\x99s Rep.'
GDP_growth = GDP_growth[GDP_growth['Country Name'].isin(input_df['Country Name'].values)]


MORT_U5 = pd.read_csv('MORT_U5.csv')
MORT_U5.drop(MORT_U5.columns[[1,2,3]], axis=1, inplace=True)
MORT_U5.loc[MORT_U5['Country Name'] == 'Korea, Dem. People\x89\xdb\xaas Rep.', 'Country Name'] = 'Korea, Dem. People\xe2\x80\x99s Rep.'
MORT_U5 = MORT_U5[MORT_U5['Country Name'].isin(countries)]

In [302]:
target_df_final

,Country Name,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,66.079189,66.242535,66.405881,66.569227,66.732574,66.895920,67.059266,67.222612,67.385958,...,74.526756,74.675732,74.818146,74.953537,76.043308,76.206654,76.370001,76.533347,76.696693,76.860039
1,Afghanistan,25.343483,25.928843,26.514204,27.099564,27.684924,28.270285,28.855645,29.441005,30.026366,...,57.833829,58.225024,58.603683,58.970829,61.050465,61.635825,62.221185,62.806546,63.391906,63.977267
2,Angola,31.276143,31.543230,31.810316,32.077403,32.344489,32.611575,32.878662,33.145748,33.412835,...,49.435732,49.847390,50.251024,50.654171,49.593188,49.941265,50.289343,50.637420,50.985497,51.333575
3,Albania,62.088492,62.337358,62.586223,62.835089,63.083955,63.332821,63.581686,63.830552,64.079418,...,76.470293,76.652073,76.840366,77.036951,77.269299,77.518165,77.767030,78.015896,78.264762,78.513627
4,United Arab Emirates,50.418938,50.965479,51.512020,52.058562,52.605103,53.151644,53.698185,54.244726,54.791268,...,76.111171,76.307756,76.494780,76.675244,78.208385,78.532944,78.857502,79.182061,79.506619,79.831178
5,Argentina,62.522313,62.745562,62.968811,63.192060,63.415309,63.638558,63.861807,64.085056,64.308305,...,75.009049,75.166268,75.324561,75.484976,76.140502,76.363751,76.587000,76.810249,77.033498,77.256747
6,Armenia,66.142346,66.292107,66.441868,66.591629,66.741390,66.891151,67.040912,67.190673,67.340434,...,73.764659,73.945000,74.095829,74.226341,74.242223,74.537270,74.832316,75.127363,75.422409,75.717456
7,Antigua and Barbuda,60.271160,60.534626,60.798091,61.061556,61.325022,61.588487,61.851952,62.115418,62.378883,...,74.803220,74.979171,75.147024,75.308780,76.342546,76.606012,76.869477,77.132942,77.396408,77.659873
8,Australia,66.799305,67.049667,67.300029,67.550392,67.800754,68.051117,68.301479,68.551842,68.802204,...,81.292683,81.395122,81.543902,81.695122,82.071413,82.321775,82.572137,82.822500,83.072862,83.323225
9,Austria,65.465348,65.715528,65.965707,66.215887,66.466067,66.716246,66.966426,67.216606,67.466785,...,80.180488,80.431707,80.331707,80.580488,80.726309,80.976488,81.226668,81.476848,81.727028,81.977207
10,Azerbaijan,61.631181,61.731393,61.831605,61.931817,62.032029,62.132241,62.232453,62.332665,62.432877,...,69.756512,70.063951,70.293683,70.451317,69.227565,69.412266,69.596967,69.781667,69.966368,70.151069
11,Burundi,39.105532,39.350848,39.596164,39.841480,40.086796,40.332112,40.577428,40.822744,41.068060,...,53.456073,53.891024,54.351220,54.829195,54.069805,54.315121,54.560437,54.805753,55.051068,55.296384
12,Belgium,67.039116,67.255966,67.472816,67.689666,67.906515,68.123365,68.340215,68.557065,68.773915,...,79.782927,79.680488,79.982927,80.182927,80.266961,80.483811,80.700661,80.917510,81.134360,81.351210
13,Benin,33.900831,34.340176,34.779521,35.218866,35.658211,36.097556,36.536901,36.976246,37.415591,...,57.867390,58.204512,58.491268,58.729707,60.700876,61.140221,61.579566,62.018911,62.458256,62.897601
14,Burkina Faso,29.285444,29.804157,30.322869,30.841582,31.360294,31.879007,32.397719,32.916432,33.435144,...,55.188805,55.902293,56.524976,57.051390,55.980184,56.352869,56.725555,57.098241,57.470926,57.843612
15,Bangladesh,41.180747,41.557442,41.934138,42.310833,42.687529,43.064225,43.440920,43.817616,44.194312,...,68.859976,69.277854,69.683780,70.080293,71.192903,71.787815,72.382727,72.977640,73.572552,74.167464
16,Bulgaria,70.006138,70.046152,70.086165,70.126178,70.166192,70.206205,70.246219,70.286232,70.326246,...,72.663415,72.963415,73.412195,73.512195,72.446957,72.486970,72.526984,72.566997,72.607011,72.647024
17,Bahrain,49.490307,50.167628,50.844950,51.522272,52.199593,52.876915,53.554236,54.231558,54.908880,...,75.707756,75.847512,75.987780,76.127561,77.435601,77.679301,77.923001,78.166701,78.410401,78.654101
18,"Bahamas, The",61.353284,61.577795,61.802306,62.026816,62.251327,62.475837,62.700348,62.924859,63.149369,...,74.059463,74.247439,74.423902,74.592390,75.048431,75.272942,75.497452,75.721963,75.946473,76.170984
19,Bosnia and Herzegovina,59.790416,60.092973,60.395531,60.698088,61.000645,61.303203,61.605760,61.908317,62.210875,...,75.371488,75.511976,75.657366,75.807683,76.504648,76.737534,76.970421,77.203308,77.436194,77.669081
20,Belarus,69.977553,69.969381,69.961209,69.953036,69.944864,69.936692,69.928520,69.920347,69.912175,...,70.203415,70.456098,70.407317,70.404878,69.479046,69.470874,69.462702,69.454530,69.446357,69.438185
21,Belize,59.361585,59.665109,59.968633,60.272156,60.575680,60.879204,61.182727,61.486251,61.789775,...,69.452000,69.594220,69.703073,69.782049,69.471639,69.438967,69.406295,69.373623,69.340951,69.308279
22,Bermuda,65.181139,65.424323,65.667507,65.910691,66.153875,66.397058,66.640242,66.883426,67.126610,...,78.934146,79.236585,79.388439,79.288537,80.015360,80.258544,80.501728,80.744912,80.988096,81.231280
23,Bolivia,35.660050,36.158187,36.656324,37.154462,37.652599,38.150737,38.648874,39.147011,39.645149,...,64.694122,65.273805,65.848000,66.407756,66.046429,66.544567,67.042704,67.540841,68.038979,68.537116
24,Brazil,51.171502,51.540909,51.910316,52.279723,52.649130,53.018537,53.387944,53.757351,54.126758,...,72.414829,72.695415,72.978024,73.264146,73.705328,74.074735,74.444142,74.813549,75.182956,75.552363
25,Barbados,59.907392,60.175038,60.442683,60.710329,60.977975,61.245621,61.513266,61.780912,62.048558,...,74.356415,74.519195,74.682488,74.845293,76.233783,76.501428,76.769074,77.036720,77.304366,77.572011
26,Brunei Darussalam,61.347666,61.628605,61.909543,62.190482,62.471421,62.752359,63.033298,63.314237,63.595175,...,76.675561,76.956756,77.268293,77.598268,78.484921,78.765860,79.046799,79.327737,79.608676,79.889614
27,Bhutan,22.320382,23.082576,23.844770,24.606964,25.369158,26.131352,26.893546,27.655740,28.417934,...,66.293098,66.885024,67.416659,67.892415,68.814218,69.576412,70.338606,71.100800,71.862994,72.625188
28,Botswana,44.512072,45.035532,45.558993,46.082453,46.605914,47.129374,47.652835,48.176296,48.699756,...,59.074561,60.958585,62.417098,63.402293,64.805901,66.594284,68.382667,70.171049,71.959432,73.747815
29,Central African Republic,32.205613,32.707105,33.208596,33.710088,34.211580,34.713072,35.214563,35.716055,36.217547,...,45.687390,46.284000,46.934976,47.625317,45.175253,45.102941,45.030630,44.958318,44.886006,44.813694
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,Seychelles,63.944382,64.099597,64.254813,64.410028,64.565243,64.720459,64.875674,65.030889,65.186105,...,73.192683,73.163415,73.034146,73.197561,73.412517,73.567732,73.722948,73.878163,74.033378,74.188594
173,Syrian Arab Republic,48.902799,49.432944,49.963090,50.493236,51.023381,51.553527,52.083673,52.613818,53.143964,...,74.246073,73.797244,73.120415,72.307439,76.339505,76.673563,77.007622,77.341680,77.675739,78.009797
174,Chad,37.284834,37.500968,37.717101,37.933235,38.149369,38.365503,38.581636,38.797770,39.013904,...,48.559220,48.951585,49.393171,49.862073,50.468993,50.685126,50.901260,51.117394,51.333528,51.549661
175,Togo,37.290399,37.759230,38.228061,38.696893,39.165724,39.634555,40.103386,40.572217,41.041048,...,55.433439,56.005902,56.630610,57.281561,55.932904,56.003487,56.074071,56.144654,56.215238,56.285821
176,Thailand,51.401377,51.830266,52.259154,52.688042,53.116930,53.545818,53.974706,54.403594,54.832482,...,72.874439,73.188439,73.461732,73.694366,75.089047,75.418955,75.748863,76.078771,76.408679,76.738587
177,Tajikistan,56.072152,56.249545,56.426938,56.604332,56.781725,56.959118,57.136512,57.313905,57.491298,...,67.207488,67.714585,68.170537,68.563390,66.893143,67.070536,67.247929,67.425322,67.602716,67.780109
178,Turkmenistan,54.445436,54.637231,54.829027,55.020823,55.212618,55.404414,55.596210,55.788005,55.979801,...,64.638829,64.756073,64.883537,65.021244,66.144972,66.336768,66.528564,66.720360,66.912155,67.103951
179,Timor-Leste,28.112387,28.686933,29.261479,29.836024,30.410570,30.985116,31.559662,32.134208,32.708754,...,65.824195,66.457829,66.946683,67.308390,69.981657,71.004506,72.027355,73.050204,74.073053,75.095902
180,Tonga,60.873560,61.075836,61.278113,61.480389,61.682665,61.884941,62.087217,62.289493,62.491770,...,71.737000,71.883195,72.031756,72.182610,73.212406,73.414682,73.616958,73.819234,74.021511,74.223787
181,Trinidad and Tobago,63.070720,63.185894,63.301067,63.416241,63.531414,63.646588,63.761762,63.876935,63.992109,...,69.259659,69.428927,69.610585,69.797561,70.096308,70.211482,70.326655,70.441829,70.557002,70.672176
182,Tunisia,33.159961,34.086232,35.012504,35.938776,36.865048,37.791319,38.717591,39.643863,40.570134,...,74.202439,74.302439,74.451220,74.602439,77.172107,77.598761,78.025416,78.452071,78.878725,79.305380
183,Turkey,40.767539,41.347516,41.927493,42.507470,43.087447,43.667424,44.247401,44.827378,45.407356,...,73.177073,73.500756,73.803220,74.090927,76.146144,76.726121,77.306098,77.886075,78.466052,79.046029
184,Tanzania,42.169224,42.401863,42.634501,42.867140,43.099779,43.332418,43.565057,43.797695,44.030334,...,58.077780,59.314707,60.509512,61.625610,60.108278,60.846067,61.583857,62.321646,63.059435,63.797224
185,Uganda,43.218204,43.471770,43.725336,43.978902,44.232469,44.486035,44.739601,44.993167,45.246734,...,53.654146,54.461976,55.182098,55.836659,55.617078,56.395669,57.174259,57.952850,58.731440,59.510031
186,Ukraine,70.444711,70.406716,70.368721,70.330726,70.292731,70.254736,70.216741,70.178745,70.140750,...,68.222195,68.251463,69.190000,70.265366,68.127010,68.089014,68.051019,68.013024,67.975029,67.937034
187,Uruguay,65.181605,65.367291,65.552977,65.738663,65.924349,66.110035,66.295720,66.481406,66.667092,...,75.951024,76.101073,76.248585,76.394610,76.508440,76.694126,76.879811,77.065497,77.251183,77.436869
188,United States,67.755780,67.937567,68.119354,68.301141,68.482928,68.664715,68.846503,69.028290,69.210077,...,77.987805,78.039024,78.390244,78.541463,78.844788,79.026575,79.208362,79.390150,79.571937,79.753724
189,Uzbekistan,59.773584,59.924897,60.076210,60.227524,60.378837,60.530150,60.681464,60.832777,60.984090,...,67.531220,67.634195,67.744561,67.861293,69.003696,69.155009,69.306322,69.457636,69.608949,69.760262
190,St. Vincent and the Grenadines,59.551386,59.791033,60.030680,60.270327,60.509975,60.749622,60.989269,61.228916,61.468563,...,71.699415,71.931732,72.150073,72.346390,73.495493,73.708165,73.920837,74.133510,74.346182,74.558854
191,"Venezuela, RB",59.211670,59.473785,59.735900,59.998016,60.260131,60.522246,60.784361,61.046476,61.308591,...,73.388902,73.476244,73.568000,73.671610,75.200692,75.462807,75.724922,75.987037,76.249152,76.511267
192,Virgin Islands (U.S.),61.503409,61.820909,62.138408,62.455908,62.773408,63.090908,63.408408,63.725907,64.043407,...,78.824390,78.924390,79.073171,79.173171,80.870896,81.188395,81.505895,81.823395,82.140895,82.458395
193,Vietnam,59.269318,59.354899,59.440479,59.526060,59.611641,59.697222,59.782802,59.868383,59.953964,...,74.483854,74.653098,74.822610,74.990366,75.825038,76.085449,76.345859,76.606270,76.866681,77.127092
194,Vanuatu,42.941612,43.432911,43.924211,44.415510,44.906809,45.398108,45.889408,46.380707,46.872006,...,69.948732,70.254756,70.555829,70.849951,72.910866,73.402166,73.893465,74.384764,74.876063,75.367363
195,West Bank and Gaza,60.578969,60.777284,60.975599,61.173913,61.372228,61.570543,61.768858,61.967173,62.165488,...,71.747049,71.894951,72.051098,72.214927,72.676177,72.874492,73.072807,73.271122,73.469436,73.667751
196,Samoa,45.823019,46.289704,46.756389,47.223074,47.689760,48.156445,48.623130,49.089815,49.556501,...,71.560780,71.844293,72.130683,72.417000,74.290818,74.757503,75.224188,75.690873,76.157559,76.624244
197,"Yemen, Rep.",25.758887,26.560016,27.361145,28.162274,28.963403,29.764532,30.565661,31.366790,32.167919,...,61.954805,62.211366,62.485341,62.768732,65.117873,65.538606,65.959340,66.380074,66.800807,67.221541
198,South Africa,43.807195,44.267058,44.726920,45.186783,45.646645,46.106507,46.566370,47.026232,47.486095,...,51.996512,52.636024,53.467098,54.390756,51.232140,50.873832,50.515524,50.157216,49.798908,49.440600
199,"Congo, Dem. Rep.",38.095839,38.367101,38.638363,38.909625,39.180887,39.452149,39.723411,39.994673,40.265934,...,55.064415,55.724000,56.337073,56.896146,54.642817,54.914079,55.185341,55.456603,55.727864,55.999126
200,Zambia,40.117310,40.589609,41.061908,41.534207,42.006506,42.478805,42.951104,43.423403,43.895703,...,52.477146,53.905634,55.214171,56.383854,56.094829,57.197570,58.300311,59.403052,60.505793,61.608534
201,Zimbabwe,47.061630,47.471173,47.880716,48.290259,48.699802,49.109345,49.518888,49.928431,50.337973,...,44.177756,45.804488,47.624659,49.574659,47.473404,48.315913,49.158422,50.000932,50.843441,51.685950

In [303]:
# MORT_U5.head()

In [304]:
Target_Columns = ['Country Name']+ [str(year) for  year in range(1950,2017)]
target_df_final = pd.DataFrame()
for year in Target_Columns:
    if year in target_df.columns:
        target_df_final['%s' % (year,)] = target_df['%s' % (year,)]
    else:
        target_df_final['%s' % (year,)] = np.nan

In [305]:
Input_Columns = ['Country Name']+ [str(year) for  year in range(1950,2017)]
input_df_final = pd.DataFrame()
for year in Input_Columns:
    if year in GDP_growth.columns:
        input_df_final['%s' % (year,)] = GDP_growth['%s' % (year,)]
    else:
        input_df_final['%s' % (year,)] = np.nan

In [306]:
input_df_final.fillna(0.0, inplace=True)

In [307]:
input_df_final

,Country Name,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-3.654626,-6.881302,-5.653502,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13.740205,3.611368,21.020649,8.433290,6.113685,14.434741,1.959123,1.312531,1.519911,0.0
3,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.593054,13.817146,2.412870,3.407655,3.918597,5.155441,6.813586,4.804473,2.997704,0.0
4,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.900000,7.530000,3.350000,3.710000,2.550000,1.420000,1.110000,2.000000,2.560000,0.0
6,United Arab Emirates,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.184390,3.191836,-5.242922,1.635449,5.207799,6.893596,4.321360,4.570290,3.182678,0.0
7,Argentina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.015745,4.093862,-6.013355,10.353567,6.147486,-1.052874,2.302484,-2.558477,2.372296,0.0
8,Armenia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13.749202,6.900000,-14.149989,2.200000,4.700000,7.200000,3.300000,3.500000,3.000000,0.0
10,Antigua and Barbuda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.498944,0.071111,-12.036015,-7.142991,-1.793436,4.019542,-0.346260,4.821980,3.664121,0.0
11,Australia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.757658,3.706700,1.819678,2.018182,2.379561,3.632720,2.440049,2.499851,2.257825,0.0
12,Austria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.621510,1.547264,-3.799075,1.928673,2.808000,0.757314,0.321251,0.353471,0.862105,0.0
13,Azerbaijan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.049000,10.772421,9.410654,4.854339,0.065923,2.200000,5.796678,2.000000,1.100000,0.0
14,Burundi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.785832,5.048119,3.468425,3.785903,4.191626,4.019366,4.594054,4.660918,-2.535866,0.0
15,Belgium,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.397472,0.747103,-2.284879,2.694826,1.796838,0.158657,0.003056,1.295473,1.373937,0.0
16,Benin,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.986516,4.893394,2.319227,2.116850,2.962750,4.643023,6.878996,6.541487,5.240447,0.0
17,Burkina Faso,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.655005,7.294498,2.962014,8.446325,6.521769,6.452675,3.649305,4.047796,3.979542,0.0
18,Bangladesh,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.058636,6.013790,5.045125,5.571802,6.464384,6.521435,6.013596,6.061093,6.552633,0.0
19,Bulgaria,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.675351,5.647005,-4.219727,0.054558,1.583974,0.237074,1.281885,1.550000,2.967135,0.0
20,Bahrain,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.292444,6.245128,2.539772,4.334407,2.100184,3.588705,5.412938,4.480935,2.926567,0.0
21,"Bahamas, The",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.446522,-2.323937,-4.175259,1.538779,0.612903,2.217313,0.022030,1.022786,1.220484,0.0
22,Bosnia and Herzegovina,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.728757,5.481508,-2.869881,0.767254,0.908248,-0.933188,2.394192,1.081876,3.157576,0.0
23,Belarus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.600000,10.200000,0.200000,7.740781,5.543711,1.731391,1.073601,1.723086,-3.887699,0.0
24,Belize,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.105586,3.229101,0.799202,3.321037,2.102219,3.740823,1.313220,4.081916,1.918486,0.0
25,Bermuda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.845890,1.527894,-5.284177,-2.094114,-3.339494,-4.834540,-2.511154,0.000000,0.000000,0.0
26,Bolivia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.564384,6.148497,3.357001,4.126723,5.204093,5.122275,6.796012,5.460570,3.961728,0.0
27,Brazil,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.072284,5.093767,-0.126147,7.528797,3.910255,1.915459,3.015141,0.103371,-3.847362,0.0
28,Barbados,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.700985,0.440141,-4.031551,0.273973,0.728597,0.271248,0.000000,0.180343,0.990099,0.0
29,Brunei Darussalam,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.154581,-1.939715,-1.764536,2.598966,3.429818,0.948355,-1.751961,-2.340000,-0.500000,0.0
30,Bhutan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,17.925825,4.768354,6.657224,11.730854,7.890914,5.071710,2.142497,5.458817,3.254255,0.0
31,Botswana,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.280147,6.242117,-7.652310,8.563632,6.048316,4.456466,9.860293,3.203915,-0.254733,0.0
32,Central African Republic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.607562,2.054127,1.709221,3.046657,3.300740,2.898541,-37.011957,-1.257108,5.486459,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
223,Seychelles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.421436,-2.146893,-1.105246,5.954962,7.887280,6.610244,6.049822,3.316985,3.497814,0.0
224,Syrian Arab Republic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
226,Chad,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.271500,3.052692,4.217696,13.550101,0.082870,8.882576,5.700001,6.899985,1.800000,0.0
229,Togo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.290454,2.225480,3.510297,3.995679,4.883764,4.820344,3.967793,5.937491,5.475269,0.0
230,Thailand,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.435093,1.725668,-0.738280,7.506711,0.833682,7.230959,2.702117,0.817633,2.819683,0.0
231,Tajikistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.800002,7.899998,3.800001,6.500000,7.399999,7.499999,7.400001,6.699251,4.200000,0.0
232,Turkmenistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.059299,14.700000,6.100000,9.200000,14.700000,11.100000,10.200000,10.300000,6.500000,0.0
235,Timor-Leste,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.447811,14.199396,12.962963,9.367681,9.528908,6.353861,2.757353,5.500000,4.251000,0.0
236,Tonga,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-4.571113,2.456249,1.099574,4.165691,2.019125,0.546957,-2.675542,2.143955,0.000000,0.0
239,Trinidad and Tobago,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.754190,3.390421,-4.390592,-0.092862,0.006985,1.366074,1.739761,0.816480,1.006274,0.0
240,Tunisia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.709620,4.237777,3.043449,3.510609,-2.383919,3.700000,2.300000,2.300000,0.800000,0.0
241,Turkey,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.668579,0.658839,-4.825876,9.156954,8.772746,2.127461,4.192509,3.020118,3.984859,0.0
243,Tanzania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.464381,5.566596,5.382346,6.358886,7.904508,5.141014,7.263060,6.965133,6.967872,0.0
244,Uganda,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.412426,8.708752,7.251045,5.170343,9.673225,4.411260,3.270737,4.815273,5.042981,0.0
245,Ukraine,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.900001,2.300000,-14.800000,4.200000,5.200000,0.200000,0.000000,-6.600003,-9.899983,0.0
247,Uruguay,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.541511,7.176145,4.243494,7.803410,5.162133,3.538179,4.637539,3.238791,0.982259,0.0
248,United States,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.778570,-0.291621,-2.775530,2.531921,1.601455,2.224031,1.489525,2.427796,2.425971,0.0
249,Uzbekistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.921154,9.000000,8.100000,8.500000,8.300000,8.200000,8.000000,8.100000,8.000000,0.0
250,St. Vincent and the Grenadines,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.617029,6.731968,-2.099061,-3.365117,-0.423644,1.380494,1.670008,0.656614,1.451904,0.0
251,"Venezuela, RB",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.753579,5.277854,-3.202303,-1.488791,4.176425,5.625957,1.343094,-3.894386,-5.700000,0.0
253,Virgin Islands (U.S.),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
254,Vietnam,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,7.129504,5.661771,5.397898,6.423238,6.240303,5.247367,5.421883,5.983655,6.679289,0.0
255,Vanuatu,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.175677,6.448521,3.312816,1.629082,1.223226,1.754750,1.969146,2.304347,0.000000,0.0
256,West Bank and Gaza,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-1.727004,-8.590176,20.940788,2.337462,7.835718,14.536035,-4.280021,-1.091389,12.393243,0.0
258,Samoa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.322642,1.009087,-4.808272,0.479159,5.778544,0.402104,-1.933859,1.196147,1.634776,0.0
259,"Yemen, Rep.",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.338428,4.014389,4.134838,3.317465,-15.088393,2.469879,4.155706,0.000000,0.000000,0.0
260,South Africa,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.360474,3.191044,-1.538089,3.039747,3.212452,2.219824,2.212354,1.548701,1.283296,0.0
261,"Congo, Dem. Rep.",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.259470,6.225900,2.855060,7.078889,6.864630,7.157860,8.503503,8.969479,6.916188,0.0
262,Zambia,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.352436,7.773896,9.220348,10.298206,5.615583,7.572564,5.131819,5.024890,3.221576,0.0
263,Zimbabwe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-3.653327,-17.668947,5.984391,11.375921,11.905408,10.565204,4.484095,3.848290,1.073432,0.0

In [308]:
target_copy = target_df_final.iloc[:, 1:].copy()

In [309]:
target_copy.columns = range(1950, 2017)

In [310]:
target_copy.interpolate(axis=1, method = 'linear', order = 1, limit = 10000, inplace = True)

In [195]:
target_copy.interpolate(axis=1, limit_direction='both', method = 'spline', order = 1, limit = 10000, inplace = True)

In [311]:
target_df_final.iloc[:, 1:] = target_copy.values

In [312]:
target_df_final

,Country Name,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.526756,74.675732,74.818146,74.953537,74.953537,74.953537,74.953537,74.953537,74.953537,74.953537
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.833829,58.225024,58.603683,58.970829,58.970829,58.970829,58.970829,58.970829,58.970829,58.970829
2,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49.435732,49.847390,50.251024,50.654171,50.654171,50.654171,50.654171,50.654171,50.654171,50.654171
3,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76.470293,76.652073,76.840366,77.036951,77.036951,77.036951,77.036951,77.036951,77.036951,77.036951
4,United Arab Emirates,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76.111171,76.307756,76.494780,76.675244,76.675244,76.675244,76.675244,76.675244,76.675244,76.675244
5,Argentina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.009049,75.166268,75.324561,75.484976,75.484976,75.484976,75.484976,75.484976,75.484976,75.484976
6,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73.764659,73.945000,74.095829,74.226341,74.226341,74.226341,74.226341,74.226341,74.226341,74.226341
7,Antigua and Barbuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.803220,74.979171,75.147024,75.308780,75.308780,75.308780,75.308780,75.308780,75.308780,75.308780
8,Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81.292683,81.395122,81.543902,81.695122,81.695122,81.695122,81.695122,81.695122,81.695122,81.695122
9,Austria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,80.180488,80.431707,80.331707,80.580488,80.580488,80.580488,80.580488,80.580488,80.580488,80.580488
10,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,69.756512,70.063951,70.293683,70.451317,70.451317,70.451317,70.451317,70.451317,70.451317,70.451317
11,Burundi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53.456073,53.891024,54.351220,54.829195,54.829195,54.829195,54.829195,54.829195,54.829195,54.829195
12,Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,79.782927,79.680488,79.982927,80.182927,80.182927,80.182927,80.182927,80.182927,80.182927,80.182927
13,Benin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,57.867390,58.204512,58.491268,58.729707,58.729707,58.729707,58.729707,58.729707,58.729707,58.729707
14,Burkina Faso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.188805,55.902293,56.524976,57.051390,57.051390,57.051390,57.051390,57.051390,57.051390,57.051390
15,Bangladesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68.859976,69.277854,69.683780,70.080293,70.080293,70.080293,70.080293,70.080293,70.080293,70.080293
16,Bulgaria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72.663415,72.963415,73.412195,73.512195,73.512195,73.512195,73.512195,73.512195,73.512195,73.512195
17,Bahrain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.707756,75.847512,75.987780,76.127561,76.127561,76.127561,76.127561,76.127561,76.127561,76.127561
18,"Bahamas, The",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.059463,74.247439,74.423902,74.592390,74.592390,74.592390,74.592390,74.592390,74.592390,74.592390
19,Bosnia and Herzegovina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.371488,75.511976,75.657366,75.807683,75.807683,75.807683,75.807683,75.807683,75.807683,75.807683
20,Belarus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,70.203415,70.456098,70.407317,70.404878,70.404878,70.404878,70.404878,70.404878,70.404878,70.404878
21,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,69.452000,69.594220,69.703073,69.782049,69.782049,69.782049,69.782049,69.782049,69.782049,69.782049
22,Bermuda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78.934146,79.236585,79.388439,79.288537,79.288537,79.288537,79.288537,79.288537,79.288537,79.288537
23,Bolivia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.694122,65.273805,65.848000,66.407756,66.407756,66.407756,66.407756,66.407756,66.407756,66.407756
24,Brazil,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72.414829,72.695415,72.978024,73.264146,73.264146,73.264146,73.264146,73.264146,73.264146,73.264146
25,Barbados,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.356415,74.519195,74.682488,74.845293,74.845293,74.845293,74.845293,74.845293,74.845293,74.845293
26,Brunei Darussalam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76.675561,76.956756,77.268293,77.598268,77.598268,77.598268,77.598268,77.598268,77.598268,77.598268
27,Bhutan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.293098,66.885024,67.416659,67.892415,67.892415,67.892415,67.892415,67.892415,67.892415,67.892415
28,Botswana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,59.074561,60.958585,62.417098,63.402293,63.402293,63.402293,63.402293,63.402293,63.402293,63.402293
29,Central African Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.687390,46.284000,46.934976,47.625317,47.625317,47.625317,47.625317,47.625317,47.625317,47.625317
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,Seychelles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73.192683,73.163415,73.034146,73.197561,73.197561,73.197561,73.197561,73.197561,73.197561,73.197561
173,Syrian Arab Republic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.246073,73.797244,73.120415,72.307439,72.307439,72.307439,72.307439,72.307439,72.307439,72.307439
174,Chad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.559220,48.951585,49.393171,49.862073,49.862073,49.862073,49.862073,49.862073,49.862073,49.862073
175,Togo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.433439,56.005902,56.630610,57.281561,57.281561,57.281561,57.281561,57.281561,57.281561,57.281561
176,Thailand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,72.874439,73.188439,73.461732,73.694366,73.694366,73.694366,73.694366,73.694366,73.694366,73.694366
177,Tajikistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.207488,67.714585,68.170537,68.563390,68.563390,68.563390,68.563390,68.563390,68.563390,68.563390
178,Turkmenistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.638829,64.756073,64.883537,65.021244,65.021244,65.021244,65.021244,65.021244,65.021244,65.021244
179,Timor-Leste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.824195,66.457829,66.946683,67.308390,67.308390,67.308390,67.308390,67.308390,67.308390,67.308390
180,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71.737000,71.883195,72.031756,72.182610,72.182610,72.182610,72.182610,72.182610,72.182610,72.182610
181,Trinidad and Tobago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,69.259659,69.428927,69.610585,69.797561,69.797561,69.797561,69.797561,69.797561,69.797561,69.797561
182,Tunisia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.202439,74.302439,74.451220,74.602439,74.602439,74.602439,74.602439,74.602439,74.602439,74.602439
183,Turkey,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73.177073,73.500756,73.803220,74.090927,74.090927,74.090927,74.090927,74.090927,74.090927,74.090927
184,Tanzania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,58.077780,59.314707,60.509512,61.625610,61.625610,61.625610,61.625610,61.625610,61.625610,61.625610
185,Uganda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,53.654146,54.461976,55.182098,55.836659,55.836659,55.836659,55.836659,55.836659,55.836659,55.836659
186,Ukraine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68.222195,68.251463,69.190000,70.265366,70.265366,70.265366,70.265366,70.265366,70.265366,70.265366
187,Uruguay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.951024,76.101073,76.248585,76.394610,76.394610,76.394610,76.394610,76.394610,76.394610,76.394610
188,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,77.987805,78.039024,78.390244,78.541463,78.541463,78.541463,78.541463,78.541463,78.541463,78.541463
189,Uzbekistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.531220,67.634195,67.744561,67.861293,67.861293,67.861293,67.861293,67.861293,67.861293,67.861293
190,St. Vincent and the Grenadines,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71.699415,71.931732,72.150073,72.346390,72.346390,72.346390,72.346390,72.346390,72.346390,72.346390
191,"Venezuela, RB",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73.388902,73.476244,73.568000,73.671610,73.671610,73.671610,73.671610,73.671610,73.671610,73.671610
192,Virgin Islands (U.S.),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,78.824390,78.924390,79.073171,79.173171,79.173171,79.173171,79.173171,79.173171,79.173171,79.173171
193,Vietnam,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,74.483854,74.653098,74.822610,74.990366,74.990366,74.990366,74.990366,74.990366,74.990366,74.990366
194,Vanuatu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,69.948732,70.254756,70.555829,70.849951,70.849951,70.849951,70.849951,70.849951,70.849951,70.849951
195,West Bank and Gaza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71.747049,71.894951,72.051098,72.214927,72.214927,72.214927,72.214927,72.214927,72.214927,72.214927
196,Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,71.560780,71.844293,72.130683,72.417000,72.417000,72.417000,72.417000,72.417000,72.417000,72.417000
197,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.954805,62.211366,62.485341,62.768732,62.768732,62.768732,62.768732,62.768732,62.768732,62.768732
198,South Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,51.996512,52.636024,53.467098,54.390756,54.390756,54.390756,54.390756,54.390756,54.390756,54.390756
199,"Congo, Dem. Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.064415,55.724000,56.337073,56.896146,56.896146,56.896146,56.896146,56.896146,56.896146,56.896146
200,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52.477146,53.905634,55.214171,56.383854,56.383854,56.383854,56.383854,56.383854,56.383854,56.383854
201,Zimbabwe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.177756,45.804488,47.624659,49.574659,49.574659,49.574659,49.574659,49.574659,49.574659,49.574659

In [197]:
input_df_final.head()

,Country Name,1950,1951,1952,1953,1954,1955,1956,1957,1958,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,Aruba,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,-3.654626,-6.881302,-5.653502,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,Afghanistan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,13.740205,3.611368,21.020649,8.433290,6.113685,14.434741,1.959123,1.312531,1.519911,0.0
3,Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.593054,13.817146,2.412870,3.407655,3.918597,5.155441,6.813586,4.804473,2.997704,0.0
4,Albania,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.900000,7.530000,3.350000,3.710000,2.550000,1.420000,1.110000,2.000000,2.560000,0.0
6,United Arab Emirates,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3.184390,3.191836,-5.242922,1.635449,5.207799,6.893596,4.321360,4.570290,3.182678,0.0

In [198]:
np.sum(input_df_final.isnull())

Country Name    0
1950            0
1951            0
1952            0
1953            0
1954            0
1955            0
1956            0
1957            0
1958            0
1959            0
1960            0
1961            0
1962            0
1963            0
1964            0
1965            0
1966            0
1967            0
1968            0
1969            0
1970            0
1971            0
1972            0
1973            0
1974            0
1975            0
1976            0
1977            0
1978            0
               ..
1987            0
1988            0
1989            0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
2012            0
2013            0
2014            0
2015            0
2016            0
dtype: int64

In [199]:
target_data_long = pd.melt(target_df_final, id_vars=['Country Name'], var_name = 'Year', value_name='LifeExp')
input_data_long = pd.melt(input_df_final, id_vars=['Country Name'], var_name = 'Year', value_name='GDP_Growth')

In [200]:
target_data_long.head()

           Country Name  Year    LifeExp
0                 Aruba  1950  66.079189
1           Afghanistan  1950  25.343483
2                Angola  1950  31.276143
3               Albania  1950  62.088492
4  United Arab Emirates  1950  50.418938

In [201]:
target_data_long.tail()

           Country Name  Year    LifeExp
13529       Yemen, Rep.  2016  67.221541
13530      South Africa  2016  49.440600
13531  Congo, Dem. Rep.  2016  55.999126
13532            Zambia  2016  61.608534
13533          Zimbabwe  2016  51.685950

In [202]:
input_data_long.head()

           Country Name  Year  GDP_Growth
0                 Aruba  1950         0.0
1           Afghanistan  1950         0.0
2                Angola  1950         0.0
3               Albania  1950         0.0
4  United Arab Emirates  1950         0.0

In [203]:
input_data_long.tail()

           Country Name  Year  GDP_Growth
13529       Yemen, Rep.  2016         0.0
13530      South Africa  2016         0.0
13531  Congo, Dem. Rep.  2016         0.0
13532            Zambia  2016         0.0
13533          Zimbabwe  2016         0.0

In [204]:
np.sum(target_data_long.isnull())

Country Name    0
Year            0
LifeExp         0
dtype: int64

In [205]:
np.sum(input_data_long.isnull())

Country Name    0
Year            0
GDP_Growth      0
dtype: int64

In [206]:
X = input_data_long[['Country Name', 'Year', 'GDP_Growth']]
X.ix[:,'Year'] = pd.to_numeric(X.ix[:,'Year'])
Y = target_data_long[['LifeExp']]

In [207]:
X.head()

           Country Name  Year  GDP_Growth
0                 Aruba  1950         0.0
1           Afghanistan  1950         0.0
2                Angola  1950         0.0
3               Albania  1950         0.0
4  United Arab Emirates  1950         0.0

In [208]:
X.dtypes

Country Name     object
Year              int64
GDP_Growth      float64
dtype: object

In [209]:
Y.head()

     LifeExp
0  66.079189
1  25.343483
2  31.276143
3  62.088492
4  50.418938

In [210]:
VALIDATION_long = pd.melt(VALIDATION, id_vars=['Country Name'], var_name = 'Year', value_name='LifeExp')

In [211]:
VALIDATION.head()

           Country Name       1960       2011       2012       2013       2014
0                 Aruba  65.569366  75.081390  75.205756  75.328659  75.451098
2           Afghanistan  32.328512  59.327951  59.679610  60.028268  60.374463
3                Angola  32.984829  51.059317  51.464000  51.866171  52.266878
4               Albania  62.254366  77.240585  77.443976  77.640463  77.830463
6  United Arab Emirates  52.243220  76.851195  77.024146  77.195634  77.368171

In [212]:
VALIDATION_long

                       Country Name  Year    LifeExp
0                             Aruba  1960  65.569366
1                       Afghanistan  1960  32.328512
2                            Angola  1960  32.984829
3                           Albania  1960  62.254366
4              United Arab Emirates  1960  52.243220
5                         Argentina  1960  65.215537
6                           Armenia  1960  65.863463
7               Antigua and Barbuda  1960  61.782732
8                         Australia  1960  70.817073
9                           Austria  1960  68.585610
10                       Azerbaijan  1960  60.836244
11                          Burundi  1960  41.236049
12                          Belgium  1960  69.701951
13                            Benin  1960  37.278268
14                     Burkina Faso  1960  34.477902
15                       Bangladesh  1960  45.829317
16                         Bulgaria  1960  69.247561
17                          Bahrain  1960  52.089366
18                     Bahamas, The  1960  62.729049
19           Bosnia and Herzegovina  1960  60.276220
20                          Belarus  1960  67.708098
21                           Belize  1960  59.961366
22                          Bolivia  1960  42.118317
23                           Brazil  1960  54.205463
24                         Barbados  1960  60.738049
25                Brunei Darussalam  1960  62.500366
26                           Bhutan  1960  32.359366
27                         Botswana  1960  50.547732
28         Central African Republic  1960  36.482634
29                           Canada  1960  71.133171
..                              ...   ...        ...
910                          Sweden  2014  81.956098
911                       Swaziland  2014  48.934732
912            Syrian Arab Republic  2014  70.071024
913                            Chad  2014  51.555805
914                            Togo  2014  59.655805
915                        Thailand  2014  74.422024
916                      Tajikistan  2014  69.597976
917                    Turkmenistan  2014  65.598537
918                     Timor-Leste  2014  68.259146
919                           Tonga  2014  72.792195
920             Trinidad and Tobago  2014  70.440561
921                         Tunisia  2014  74.143902
922                          Turkey  2014  75.163512
923                        Tanzania  2014  64.943902
924                          Uganda  2014  58.466415
925                         Ukraine  2014  71.186585
926                         Uruguay  2014  76.986146
927                   United States  2014  78.941463
928                      Uzbekistan  2014  68.339024
929  St. Vincent and the Grenadines  2014  72.936854
930                   Venezuela, RB  2014  74.236195
931           Virgin Islands (U.S.)  2014  79.773171
932                         Vietnam  2014  75.629122
933                         Vanuatu  2014  71.918317
934                           Samoa  2014  73.511829
935                     Yemen, Rep.  2014  63.818195
936                    South Africa  2014  57.182122
937                Congo, Dem. Rep.  2014  58.659195
938                          Zambia  2014  60.047049
939                        Zimbabwe  2014  57.498317

[940 rows x 3 columns]

In [213]:
X

                         Country Name  Year  GDP_Growth
0                               Aruba  1950         0.0
1                         Afghanistan  1950         0.0
2                              Angola  1950         0.0
3                             Albania  1950         0.0
4                United Arab Emirates  1950         0.0
5                           Argentina  1950         0.0
6                             Armenia  1950         0.0
7                 Antigua and Barbuda  1950         0.0
8                           Australia  1950         0.0
9                             Austria  1950         0.0
10                         Azerbaijan  1950         0.0
11                            Burundi  1950         0.0
12                            Belgium  1950         0.0
13                              Benin  1950         0.0
14                       Burkina Faso  1950         0.0
15                         Bangladesh  1950         0.0
16                           Bulgaria  1950         0.0
17                            Bahrain  1950         0.0
18                       Bahamas, The  1950         0.0
19             Bosnia and Herzegovina  1950         0.0
20                            Belarus  1950         0.0
21                             Belize  1950         0.0
22                            Bermuda  1950         0.0
23                            Bolivia  1950         0.0
24                             Brazil  1950         0.0
25                           Barbados  1950         0.0
26                  Brunei Darussalam  1950         0.0
27                             Bhutan  1950         0.0
28                           Botswana  1950         0.0
29           Central African Republic  1950         0.0
...                               ...   ...         ...
13504                      Seychelles  2016         0.0
13505            Syrian Arab Republic  2016         0.0
13506                            Chad  2016         0.0
13507                            Togo  2016         0.0
13508                        Thailand  2016         0.0
13509                      Tajikistan  2016         0.0
13510                    Turkmenistan  2016         0.0
13511                     Timor-Leste  2016         0.0
13512                           Tonga  2016         0.0
13513             Trinidad and Tobago  2016         0.0
13514                         Tunisia  2016         0.0
13515                          Turkey  2016         0.0
13516                        Tanzania  2016         0.0
13517                          Uganda  2016         0.0
13518                         Ukraine  2016         0.0
13519                         Uruguay  2016         0.0
13520                   United States  2016         0.0
13521                      Uzbekistan  2016         0.0
13522  St. Vincent and the Grenadines  2016         0.0
13523                   Venezuela, RB  2016         0.0
13524           Virgin Islands (U.S.)  2016         0.0
13525                         Vietnam  2016         0.0
13526                         Vanuatu  2016         0.0
13527              West Bank and Gaza  2016         0.0
13528                           Samoa  2016         0.0
13529                     Yemen, Rep.  2016         0.0
13530                    South Africa  2016         0.0
13531                Congo, Dem. Rep.  2016         0.0
13532                          Zambia  2016         0.0
13533                        Zimbabwe  2016         0.0

[13534 rows x 3 columns]

In [214]:
X = pd.get_dummies(X)

In [215]:
X.head()

,Year,GDP_Growth,Country Name_Afghanistan,Country Name_Albania,Country Name_Algeria,Country Name_Angola,Country Name_Antigua and Barbuda,Country Name_Argentina,Country Name_Armenia,Country Name_Aruba,...,Country Name_Uruguay,Country Name_Uzbekistan,Country Name_Vanuatu,"Country Name_Venezuela, RB",Country Name_Vietnam,Country Name_Virgin Islands (U.S.),Country Name_West Bank and Gaza,"Country Name_Yemen, Rep.",Country Name_Zambia,Country Name_Zimbabwe
0,1950,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1950,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1950,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1950,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1950,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [317]:
VALIDATION_long.ix[:,'Year'] = pd.to_numeric(VALIDATION_long.ix[:,'Year'])

In [315]:
X_test_df = pd.concat([X.loc[(X['Country Name_%s' % (row['Country Name'])]==1) & (X['Year']==row['Year'])] for index, row in VALIDATION_long.iterrows()])
Y_test_df = VALIDATION_long['LifeExp']

In [316]:
X_test_df

,Year,GDP_Growth,Country Name_Afghanistan,Country Name_Albania,Country Name_Algeria,Country Name_Angola,Country Name_Antigua and Barbuda,Country Name_Argentina,Country Name_Armenia,Country Name_Aruba,...,Country Name_Uruguay,Country Name_Uzbekistan,Country Name_Vanuatu,"Country Name_Venezuela, RB",Country Name_Vietnam,Country Name_Virgin Islands (U.S.),Country Name_West Bank and Gaza,"Country Name_Yemen, Rep.",Country Name_Zambia,Country Name_Zimbabwe
2020,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021,1960,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022,1960,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2023,1960,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2024,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2025,1960,0.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2026,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2027,1960,0.000000,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2028,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2029,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2030,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2031,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2032,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2033,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2034,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2035,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2036,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2037,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2038,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2039,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2040,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2041,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2043,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2044,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2045,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2046,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2047,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2048,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2049,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2050,1960,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13097,2014,2.266978,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13098,2014,2.450372,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13101,2014,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13102,2014,6.899985,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13103,2014,5.937491,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13104,2014,0.817633,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13105,2014,6.699251,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13106,2014,10.300000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13107,2014,5.500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13108,2014,2.143955,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13109,2014,0.816480,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13110,2014,2.300000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13111,2014,3.020118,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13112,2014,6.965133,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13113,2014,4.815273,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13114,2014,-6.600003,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13115,2014,3.238791,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13116,2014,2.427796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13117,2014,8.100000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13118,2014,0.656614,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13119,2014,-3.894386,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13120,2014,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
13121,2014,5.983655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
13122,2014,2.304347,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13124,2014,1.196147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13125,2014,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
13126,2014,1.548701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13127,2014,8.969479,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13128,2014,5.024890,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13129,2014,3.848290,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### Linear Regression

In [216]:
from sklearn import linear_model
linearRegression = linear_model.LinearRegression()

In [217]:
linearRegression.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [218]:
predictions = linearRegression.predict(X)

In [219]:
print "MSE is" , sk.metrics.mean_squared_error(Y, predictions)

MSE is 13.0400145767

In [272]:
predictions = linearRegression.predict(X_test_df)
print "MSE is" , sk.metrics.mean_squared_error(Y_test_df, predictions)

MSE is 17.0967592988

### Decision Trees

In [220]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
X, Y)
tree = DecisionTreeRegressor(max_depth = 230, random_state=0)
tree.fit(X_train, y_train)
predicted_y = tree.predict(X_train)
predicted_y_test = tree.predict(X_test)
print("MSE on training set: {:.3f}".format(sk.metrics.mean_squared_error(y_train, predicted_y)))
print("MSE on test set: {:.3f}".format(sk.metrics.mean_squared_error(y_test, predicted_y_test)))
print("R^2 on training set: {:.3f}".format(tree.score(X_train, y_train))) 
print("R^2 on test set: {:.3f}".format(tree.score(X_test, y_test)))

MSE on training set: 0.000
MSE on test set: 11.314
R^2 on training set: 1.000
R^2 on test set: 0.926

In [221]:
depth_list = range(200,240)
MSE_list = []

In [222]:
kf = KFold(len(Y), n_folds=10, shuffle = True)

In [223]:
for depth in depth_list:
    
    MSE_depth_CV =[]

    for train_index, test_index in kf:
        X_train_CV, X_test_CV = X.iloc[train_index,:], X.iloc[test_index,:]
        Y_train_CV, Y_test_CV = Y.iloc[train_index,:], Y.iloc[test_index,:]
        regressor = DecisionTreeRegressor(max_depth = depth) 
        regressor.fit(X_train_CV, Y_train_CV) 
        predicted_y = regressor.predict(X_test_CV)
        MSE = sk.metrics.mean_squared_error(Y_test_CV, predicted_y)
        MSE_depth_CV.append(MSE)
    
    print depth, "k-fold CV is", np.mean(MSE_depth_CV)

200 k-fold CV is 5.22180631016
201 k-fold CV is 5.26635512979
202 k-fold CV is 5.16890551892
203 k-fold CV is 5.21000083127
204 k-fold CV is 5.24529181251
205 k-fold CV is 5.21923847507
206 k-fold CV is 5.23268989934
207 k-fold CV is 5.21718231987
208 k-fold CV is 5.22875150799
209 k-fold CV is 5.17382696274
210 k-fold CV is 5.23745307341
211 k-fold CV is 5.20428206525
212 k-fold CV is 5.21600618743
213 k-fold CV is 5.23342313748
214 k-fold CV is 5.22440174771
215 k-fold CV is 5.20169597098
216 k-fold CV is 5.17113877227
217 k-fold CV is 5.21282986061
218 k-fold CV is 5.2459174269
219 k-fold CV is 5.19999375363
220 k-fold CV is 5.26418431456
221 k-fold CV is 5.18846991623
222 k-fold CV is 5.19164003706
223 k-fold CV is 5.22469114294
224 k-fold CV is 5.25963406802
225 k-fold CV is 5.25063112361
226 k-fold CV is 5.2571125455
227 k-fold CV is 5.25104430439
228 k-fold CV is 5.21140762682
229 k-fold CV is 5.23096282955
230 k-fold CV is 5.20757225482
231 k-fold CV is 5.17652972906
232 k-fold CV is 5.2357239999
233 k-fold CV is 5.22936885635
234 k-fold CV is 5.20317331258
235 k-fold CV is 5.27263442919
236 k-fold CV is 5.20954269331
237 k-fold CV is 5.2190076826
238 k-fold CV is 5.27270658035
239 k-fold CV is 5.25990730833

In [274]:
regressor = DecisionTreeRegressor(max_depth = 230) 
regressor.fit(X, Y) 
predicted_y = regressor.predict(X)
MSE = sk.metrics.mean_squared_error(Y, predicted_y)

print "MSE is", MSE

MSE is 2.37092437014e-11

In [275]:
predictions = regressor.predict(X_test_df)
print "MSE is" , sk.metrics.mean_squared_error(Y_test_df, predictions)

MSE is 3.52230933944

### Random Forests

In [276]:
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(X, Y)
forest = RandomForestRegressor()

forest.fit(X_train, y_train.values.ravel())

predicted_y = forest.predict(X_train)
predicted_y_test = forest.predict(X_test)
print("MSE on training set: {:.3f}".format(sk.metrics.mean_squared_error(y_train, predicted_y)))
print("MSE on test set: {:.3f}".format(sk.metrics.mean_squared_error(y_test, predicted_y_test)))

print("R^2 on training set: {:.3f}".format(forest.score(X_train, y_train))) 
print("R^2 on test set: {:.3f}".format(forest.score(X_test, y_test)))

MSE on training set: 1.287
MSE on test set: 6.709
R^2 on training set: 0.991
R^2 on test set: 0.957

In [280]:
regressor = RandomForestRegressor() 
regressor.fit(X, Y.values.ravel()) 
predicted_y = regressor.predict(X)
MSE = sk.metrics.mean_squared_error(Y, predicted_y)

print "MSE is", MSE

MSE is 0.730388791387

In [281]:
predictions = regressor.predict(X_test_df)
print "MSE is" , sk.metrics.mean_squared_error(Y_test_df, predictions)

MSE is 3.59893509987

### Gradient Boosting Machines

In [227]:
from sklearn.ensemble import GradientBoostingRegressor
X_train, X_test, y_train, y_test = train_test_split(
        X,Y)
gbrt = GradientBoostingRegressor(max_depth=40)
gbrt.fit(X_train, y_train.values.ravel())

predicted_y = gbrt.predict(X_train)
predicted_y_test = gbrt.predict(X_test)
print("MSE on training set: {:.3f}".format(sk.metrics.mean_squared_error(y_train, predicted_y)))
print("MSE on test set: {:.3f}".format(sk.metrics.mean_squared_error(y_test, predicted_y_test)))

MSE on training set: 0.554
MSE on test set: 2.925

In [320]:
regressor = GradientBoostingRegressor(max_depth=100)
regressor.fit(X, Y.values.ravel()) 
predicted_y = regressor.predict(X)
MSE = sk.metrics.mean_squared_error(Y, predicted_y)

print "MSE is", MSE

MSE is 1.13972065163e-05

In [321]:
predictions = regressor.predict(X_test_df)
print "MSE is" , sk.metrics.mean_squared_error(Y_test_df, predictions)

MSE is 3.52038016352

### Neural Networks

In [82]:
# from sklearn.preprocessing import StandardScaler
# from sklearn.neural_network import MLPRegressor
# scaler = StandardScaler()

# X_scaled = scaler.fit_transform(X)

ImportError: cannot import name MLPRegressor

In [ ]:
# mlp = MLPReg(max_iter=1000, random_state=0)
# mlp.fit(X_train_scaled, y_train)
# print("Accuracy on training set: {:.3f}".format( mlp.score(X_train_scaled, y_train)))
# print("Accuracy on test set: {:.3f}".format(mlp.score(X_test_scaled, y_test)))

In [ ]:
# X = input_data_long[['Year', 'GDP']]
# Y = target_data_long[['LifeExp']]

In [323]:
# X = pd.get_dummies(X)
# X.ix[:,'Year'] = pd.to_numeric(X.ix[:,'Year']).values

In [325]:
# X.head()

   Year        GDP
0  1961   1.245086
1  1961   8.444163
2  1961   2.800000
3  1961   5.745635
4  1961  16.526856

In [326]:
# X.dtypes

Year      int64
GDP     float64
dtype: object

In [327]:
# linearRegression.fit(X,Y)
# predictions = linearRegression.predict(X)
# print "MSE is" , sk.metrics.mean_squared_error(Y, predictions)

MSE is 112.200475408

In [328]:
# print linearRegression.coef_

[[ 0.28348918 -0.05335729]]

In [491]:
# print("scikit-learn version: {}".format(sk.__version__))

scikit-learn version: 0.17.1

### AdaBoost Regressor

     LifeExp
0  65.988024
1  32.777439
2  33.386220
3  63.273463
4  53.286561

In [141]:
from sklearn.ensemble import AdaBoostRegressor
rate = [0.1]    # Learning rate; default is 1.0

for r in rate:
        regressor = AdaBoostRegressor() 
        regressor.fit(X, Y.values.ravel())
        predictions = regressor.predict(X)
        print "MSE with learning rate, %s is" % (r) , sk.metrics.mean_squared_error(Y, predictions) 
        print predictions
        print Y

MSE with learning rate, 0.1 is 116.370505845
[ 55.92313653  55.7170374   55.83168702 ...,  66.14306474  66.14306474
  63.35901665]
         LifeExp
0      65.988024
1      32.777439
2      33.386220
3      63.273463
4      53.286561
5      65.338512
6      66.284390
7      62.195415
8      70.973171
9      69.577317
10     61.239171
11     41.545463
12     70.520976
13     37.731195
14     34.938634
15     46.457927
16     70.195610
17     53.458512
18     63.072512
19     60.941585
20     68.212659
21     60.512780
22     68.897805
23     42.433439
24     54.718707
25     61.215098
26     63.048951
27     32.731024
28     50.907634
29     36.895707
...          ...
10070  73.197561
10071  72.307439
10072  49.862073
10073  57.281561
10074  73.694366
10075  68.563390
10076  65.021244
10077  67.308390
10078  72.182610
10079  69.797561
10080  74.602439
10081  74.090927
10082  61.625610
10083  55.836659
10084  70.265366
10085  76.394610
10086  78.541463
10087  67.861293
10088  72.346390
10089  73.671610
10090  79.173171
10091  74.990366
10092  70.849951
10093  72.214927
10094  72.417000
10095  62.768732
10096  54.390756
10097  56.896146
10098  56.383854
10099  49.574659

[10100 rows x 1 columns]

In [152]:
regressor = RandomForestRegressor() 
regressor.fit(X, Y.values.ravel()) 
predictions = regressor.predict(X)
MSE = sk.metrics.mean_squared_error(Y, predictions)

print "MSE is", MSE

MSE is 0.756749663491

In [37]:
X.head()

,Year,GDP,Country Name_Afghanistan,Country Name_Albania,Country Name_Algeria,Country Name_Angola,Country Name_Antigua and Barbuda,Country Name_Argentina,Country Name_Armenia,Country Name_Aruba,...,Country Name_Uruguay,Country Name_Uzbekistan,Country Name_Vanuatu,"Country Name_Venezuela, RB",Country Name_Vietnam,Country Name_Virgin Islands (U.S.),Country Name_West Bank and Gaza,"Country Name_Yemen, Rep.",Country Name_Zambia,Country Name_Zimbabwe
0,1961,1.245086,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1961,8.444163,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1961,2.800000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1961,5.745635,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1961,16.526856,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
X_train = df.iloc[:,0:280]
X_test = test_df.iloc[:,0:280]

In [5]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,270,271,272,273,274,275,276,277,278,279
0,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,40.30467,53.845657,0.0,401.0,15.0,15.52416,32.44188,0.0,377.0,3.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
Y_train = df.iloc[:,280:281]
Y_test = test_df.iloc[:,280]

In [7]:
depth = 5
regressor = DecisionTreeRegressor(max_depth=depth) 
regressor.fit(X_train, Y_train) 
predicted_y = regressor.predict(X_test)

In [8]:
sk.metrics.mean_squared_error(Y_test, predicted_y)

669.66569160245422

In [9]:
depth_list = range(1,20)
MSE_list = []

In [32]:
kf = KFold(len(Y_train), n_folds=10, shuffle = True)

In [27]:
print len(X_train), len(Y_train)

52397 52397

In [33]:
for depth in depth_list:
    
    MSE_depth_CV =[]

    for train_index, test_index in kf:
        X_train_CV, X_test_CV = X_train.iloc[train_index,:], X_train.iloc[test_index,:]
        Y_train_CV, Y_test_CV = Y_train.iloc[train_index,:], Y_train.iloc[test_index,:]
        regressor = DecisionTreeRegressor(max_depth=depth) 
        regressor.fit(X_train_CV, Y_train_CV) 
        predicted_y = regressor.predict(X_test_CV)
        MSE = sk.metrics.mean_squared_error(Y_test_CV, predicted_y)
        MSE_depth_CV.append(MSE)
    
    print depth, "k-fold CV is", np.mean(MSE_depth_CV)

1 k-fold CV is 1094.48596811
2 k-fold CV is 816.360036677
3 k-fold CV is 723.863492028
4 k-fold CV is 694.557312437
5 k-fold CV is 722.944608945
6 k-fold CV is 751.824008538
7 k-fold CV is 770.717029321
8 k-fold CV is 846.656690323
9 k-fold CV is 905.152489712
10 k-fold CV is 966.206092789
11 k-fold CV is 1030.32243944
12 k-fold CV is 1053.06401763
13 k-fold CV is 1099.489705
14 k-fold CV is 1081.98415069
15 k-fold CV is 1121.63768719
16 k-fold CV is 1090.79088817
17 k-fold CV is 1090.04682546
18 k-fold CV is 1082.8004027
19 k-fold CV is 1119.92789668

In [16]:
from StringIO import StringIO
import pydotplus 

my_tree = DecisionTreeRegressor(max_depth=5).fit(X_train_CV, Y_train_CV)
dotfile = StringIO()
sk.tree.export_graphviz(my_tree, out_file=dotfile)
graph = pydotplus.graph_from_dot_data(dotfile.getvalue())
graph.write_pdf("tree.pdf")

True

In [20]:
from IPython.display import IFrame
IFrame("tree.pdf", width=600, height=300)

# Compare to Linear Regression

In [31]:
from sklearn import linear_model

my_tree = DecisionTreeRegressor(max_depth=5).fit(X_train, Y_train)

algo = linear_model.LinearRegression()
algo.fit (X_train, Y_train)
predictions_LR = algo.predict(X_test)
predictions_DT = my_tree.predict(X_test)

MSE_LR = sk.metrics.mean_squared_error(Y_test, predictions_LR)
MSE_DT = sk.metrics.mean_squared_error(Y_test, predictions_DT)

print "MSE on the testing set using Linear Regression is ", MSE_LR
print "MSE on the testing set using the Decision Tree is ", MSE_DT

MSE on the testing set using Linear Regression is  1632.13874612
MSE on the testing set using the Decision Tree is  669.665691602

In [42]:
ridge = linear_model.Ridge (alpha = 0.1)
lasso = linear_model.Lasso(alpha = 0.1)

for model in [ridge, lasso]:
    model.fit(X_train, Y_train)
    predictions = model.predict(X_test)
    
    print "MSE on the testing set using %s is " % (model) , sk.metrics.mean_squared_error(Y_test, predictions)

MSE on the testing set using Ridge(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001) is  1631.67077
MSE on the testing set using Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=None,
   selection='cyclic', tol=0.0001, warm_start=False) is  1644.88424921